### ISSUE TITLE
Question: Setting spy permissions

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#1019]
Hejo,

I need help with the following mission: I have two groups of people. One group should be able to see commands of a plugin with /spy. The other group should also see the commands of the plugin and be able to read msgs. I somehow only manage to forbid or allow /spy completely and exclude certain people from being spied on. What is the right permission to forbid only spying on private messages, but not on commands?

Why do I need this complicated structure at all? Now reading commands from a plugin is used for training purposes and is therefore needed by a number of people. The reading of msgs interferes with the private sphere and should only be accessible to a small security group. 

I am grateful for every tip.
```

Spy:
  Enabled: true
  Command_Aliases:
  - spy
  - socialspy
  Format: '&8[Schulung] {player}: &7{message}'
  Channel_Prefix: '&8[Schulung] '
  Bungee: false
  Command_List_Works_Like_Blacklist: false
  Command_List:
  - /ad
  - /adg
  Books: true
  Signs: false
  McMMO: true
  Log_McMMO: false
  Format_PM: '&8[&5spy&8] &7[{player}] -> [{receiver}]: &7{message}'
```
ChatControl 7.10.5
PaperSpigiot 1.12.2 #1593
