### ISSUE TITLE
Question about json in messages.yml

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1071]
I used the messages.yml json thing however it prints out the whole message instead of the formatted version:
`- '{"text":"Click here for some useful commands!","clickEvent":{"action":"open_url","value":"https://google.com"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click me","color":"yellow"}]}}}'`

However, if i use that in tellraw it works. Is there something that i am doing wrong?

**Comment by kangarko** [comment]
Hey, please see https://github.com/kangarko/ChatControl-Pro/wiki/JSON#json-in-timed-messages-in-messagesyml

**Comment by LogGits** [comment]
I did, i used it to create that. however it just prints out the message. ["", {"text":"Click here for some useful commands!","clickEvent":{"action":"open_url","value":"https://google.com"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click me","color":"yellow"}]}}}]

**Comment by kangarko** [comment]
Send me your entire messages.yml

**Comment by LogGits** [comment]
```
Broadcaster:
  Enabled: true
  Mode: 2
  Prefix: '&3[Announcer]&f'
  Suffix: ''
  Delay_Seconds: 60
  Messages:
    global:
    - '["", {"text":"Click here for some useful commands!","clickEvent":{"action":"open_url","value":"https://google.com"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click me","color":"yellow"}]}}}]'
    - testing stuffs!
```

**Comment by kangarko** [comment]
Prefix should be set to [JSON] and the actual prefix needs to be added directly for each line

**Comment by kangarko** [comment]
```
Broadcaster:
  Enabled: true
  Mode: 2
  Prefix:  "[JSON]"
```
