### ISSUE TITLE
Rleation Placeholders Not Working with Hover_Event

### ISSUE THREAD

**Issue by Zendrex** [kangarko/ChatControl-Pro#1075]
Title.

Works in the regular message just fine. Just seems to break in lore messages using HOVER_EVENT.

Example:
```
    Player: 
      Message: "{player} &7» "                 
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "&7Faction: &f{factionsuuid_faction_name} &7| &f{rel_factionsuuid_relation_color}"
          - "&7Role: &f{factionsuuid_player_role_name}"
          - "&7Power: &f{factionsuuid_player_power}"
          - ""
          - "&7Click to send a PM"
      Click_Event: 
        Action: SUGGEST_COMMAND
        Value: "/msg {player} " 
```
