### ISSUE TITLE
Newcomer functionality

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1129]
The newcomer function works as expected although when the amount of points are collected, the punishment is executed twice. Settings:
```
Newcomer:
  Warn_Points_Multiplier: 2.0
...
Points:
  Enabled: true
  Smart_Warnings: true
```
Log:
```
[23:45:34] [Async Chat Thread - #132/INFO]: Set testplayer's 'swear' points from 0 -> 2
[23:45:34] [Async Chat Thread - #132/INFO]: Set testplayer's 'swear' points from 2 -> 4
```
The mute is executed twice: 
- the punishment for 2 points
- immediately after that the punishment for 4 points.
Although it works as intended, it sounds a little strange for the player to get 2 punishments for 1 thing.
