### ISSUE TITLE
Death messages 'Hide_By_Gamerule' not functional.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1143]
ChatControlPro dev 7.15.2
Paper dev 600 (Spigot 1.13.2)

```
Death_Messages:
  Enabled: true
  Prefix: '&7&lZone &f&l»&r&7 '
  Ignore_Vanished: true
  Hide_By_Gamerule: true
```

I flagged all my worlds with ``/gamerule showDeathMessages false`` with the exception of one that has it enabled. However when players die in those worlds, ChatControl is sending the death message to everyone.

I'd like to only have death messages appear when dying in a single world.
