### ISSUE TITLE
Color name Luck Perms

### ISSUE THREAD

**Issue by eryk172** [kangarko/ChatControl-Pro#1187]
Hi,
I have ChatControl Pro and Luck Perms
```
    First_Part: 
      # The message that is shown in the chat.
      # In this case the variable ends with +, meaning we insert a
      # space " " automatically if prefix is not empty. Note only few variables
      # have this special feature, see our GitHub.
      #
      #  Message: "&7{pl_prefix+}"
      Message: "{pl_prefix+}{faction}"
     # Message: "&7{pl_prefix} {pl_suffix}"
     
      # This part contains hover event which display an optional
      # message when you move your mouse over that chat part.
      #
      # Unlike the part name, you must name this "Hover_Event"
      Hover_Event: 
        # What action should happen when you put your mouse on this part?
        Action: SHOW_TEXT
        # The messages that are shown to you in game.
        Values: 
          - "{pl_prefix}&l {player}"
          - "&7✌&a Grupy&7: &f{pl_group} &8♯"

    # The second part simply displays the player's name.
    Second_Part:
      # The message that is shown in the chat.
      # If you want to show player's nick instead, use {nick}
      Message: "{luckperms_meta_name-colour}{player}&7{pl_suffix} &f"
      # And show some fancy hover text, see above.
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - "&7✉ Kliknij, aby wyslac wiadomosc PW ✔"      
        - "&8♯&b{timestamp}&8♯"  
        - "&7✌&a Gildia&7: &f{faction} &8♯"        
      # This part also contains click event feature that will 
      # write /msg <playername> into your chat when clicked.
      #
      # Unlike the part name, you must name this "Click_Event"
      Click_Event:
        # What action should happen when you click on this part?
        Action: SUGGEST_COMMAND
        # The message or value when action is fired.
        Value: '/msg {player} '
    
    # The third part that simply renders the actual chat message.
    Third_Part:
      # The message that is shown in the chat
      Message: "{message}"

  #
  # This example format is used in private messages for the sender.
  #
```
How to change color-nick for specified group?

This meta not working: 
![image](https://user-images.githubusercontent.com/47436122/57640175-0630ca00-75b2-11e9-9422-4fe2e4bba1a9.png)
