### ISSUE TITLE
Bungee Chat enabled by default

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1196]
I thought that enabled: false meant that a function will not work
```
Bungee_Chat:

  # Enable bungee chat for players after login automatically. They can turn it off with '/chc g switch'
  Enabled_By_Default: false

  Log_To_Console: true
  
  # Write to logs/bungee-chat.txt ?
  Write_To_File: true
  
  # Send a normal message directly to bungee chat if it begins with the letter below
  # Set to none to disable. Pay attention that your Range shortcut in formatting.yml is not set the same
  Shortcut: "!"
```
Players had discovered that if a message starts `!` it is being broadcasted over the bungee. Apparently it should be changed to `none` to disable this function completely

ChatControl version 8.1.3
