### ISSUE TITLE
Auto-mode @People issues

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1251]
1. For some reason people can't `@people` to start a convo but I can do it as an op. It basically just sends their message into chat tagging the player. Is there a bypass permission that causes this? 

---
2. Also Typing @playername when i do it starts a convo with that player but it auto-sends the player their `@tag` if i don't provide a message. e.g. `@Tester` it would send this(`@Tester`) to Tester. Essentially executing `/mail Tester @Tester`.

Chc pro version 8.2.6 running on paper 1.13.2 build 626.

**Comment by kangarko** [comment]
Hello,

please send me your settings.yml. Also keep in mind you must have "chatcontrol.command.tell" permission for this feature to work.

**Comment by LogGits** [comment]
Players have that permission. Also this is the settings.yml section for private message:
```yaml
Private_Messages:
  Enabled: true
  Bungee: true
  Aliases:
    Tell:
    - tell
    - msg
    - t
    - whisper
    Reply:
    - reply
    - r
    TogglePM:
    - togglepm
    - ignorepm
    - nopm
  Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver
  Register_Reply_To_Self: true
  Toast:
    Enabled: false
    Format: '&6[{sender} &8-> &6you]{dynamic_spaces}&7{message}'
  Deny_Message_Self: false
  Register_Reply_To_Receiver: true
  Auto_Start:
    Enabled: true
    Prefix: '@'
    End: exit
    Start_For_Empty_Tell_Command: false
  Deep_Search: true
  Reply_Change_Timeout: 3 seconds
```

**Comment by kangarko** [comment]
What permission plugin do you use? If it works for you as an OP, that means we have permission problem somewhere. If you use luckperms simply enable debug mode there to see which perms are being asked for and give it to your players.

**Comment by kangarko** [comment]
Closing due to inactivity, just comment below and I take a look

**Comment by LogGits** [comment]
Sorry i have been busy for a while. I am using luckperms. This is the output when the player types `@LogGits` for example:
```
[Mod]: [Cast] player1: @player2
[LP]: VB > player1 - chatcontrol.group.vip - undefined
[LP]: VB > player1 - chatcontrol.chat.write - true
[LP]: VB > player1 - chatcontrol.bypass.newcomer - undefined
[LP]: VB > player1 - chatcontrol.bypass.limit.chat - true
[LP]: VB > player1 - chatcontrol.bypass.rules.chat - undefined
[LP]: VB > player1 - chatcontrol.bypass.rules.global - undefined
[LP]: VB > player1 - chatcontrol.bypass.rules.global - undefined
[LP]: VB > player1 - chatcontrol.command.tell - true
[LP]: VB > player1 - chatcontrol.chat.read - true
[LP]: VB > player1 - chatcontrol.group.vip - undefined
[LP]: VB > player1 - chatcontrol.command.bungeechat - undefined
[LP]: VB > player1 - chatcontrol.group.vip - undefined
[LP]: VB > player1 - chatcontrol.chat.format.color.black - true
[LP]: VB > player1 - chatcontrol.chat.format.color.dark_blue - true
[LP]: VB > player1 - chatcontrol.chat.format.color.dark_green - true
[LP]: VB > player1 - chatcontrol.chat.format.color.dark_aqua - true
[LP]: VB > player1 - chatcontrol.chat.format.color.dark_purple - true
[LP]: VB > player1 - chatcontrol.chat.format.color.gold - true
[LP]: VB > player1 - chatcontrol.chat.format.color.gray - true
[LP]: VB > player1 - chatcontrol.chat.format.color.dark_gray - true
[LP]: VB > player1 - chatcontrol.chat.format.color.blue - true
[LP]: VB > player1 - chatcontrol.chat.format.color.green - true
[LP]: VB > player1 - chatcontrol.chat.format.color.aqua - true
[LP]: VB > player1 - chatcontrol.chat.format.color.red - true
[LP]: VB > player1 - chatcontrol.chat.format.color.light_purple - true
[LP]: VB > player1 - chatcontrol.chat.format.color.yellow - true
[LP]: VB > player1 - chatcontrol.chat.format.color.white - true
[LP]: VB > player1 - chatcontrol.chat.format.color.reset - true
[LP]: VB > player1 - chatcontrol.chat.format.magic - false
[LP]: VB > player1 - chatcontrol.chat.format.bold - true
[LP]: VB > player1 - chatcontrol.chat.format.strikethrough - true
[LP]: VB > player1 - chatcontrol.chat.format.underline - true
[LP]: VB > player1 - chatcontrol.chat.format.italic - true
[LP]: VB > player1 - chatcontrol.chat.format.reset - true
[LP]: VB > player1 - chatcontrol.notify.bungeechat - true
[LP]: VB > player1 - chatcontrol.bypass.rules.packets - undefined
[LP]: VB > player1 - chatcontrol.command.bungeechat - undefined
[LP]: VB > player1 - chatcontrol.command.adminchat - undefined
```
Which is automode?

**Comment by kangarko** [comment]
There is none, if player has chatcontrol.command.tell permission, they can use auto-mode. Keep in mind we don't support BungeeCord for this yet.

**Comment by LogGits** [comment]
Its on a spigot server. Players cant @ other players on the same spigot server

**Comment by kangarko** [comment]
Very strange, can't reproduce. Stupid inquiry but ensure you have Auto_Start enabled (https://i.imgur.com/LfLPz4A.png). Test if it works for an empty /tell recipientName command.

There is a chance another plugin is blocking the chat input, try changing the Checker priority to lower or higher.

**Comment by kangarko** [comment]
Closing due to inactivity

**Comment by LogGits** [comment]
Ok so this still happens on 1.14.4:
```yaml
Private_Messages:
  Enabled: true
  Bungee: true
  Aliases:
    Tell:
    - tell
    - msg
    - t
    - whisper
    Reply:
    - reply
    - r
    TogglePM:
    - togglepm
    - ignorepm
    - nopm
  Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver
  Register_Reply_To_Self: true
  Toast:
    Enabled: false
    Format: '&6[{sender} &8-> &6you]{dynamic_spaces}&7{message}'
  Deny_Message_Self: false
  Register_Reply_To_Receiver: true
  Auto_Start:
    Enabled: true
    Prefix: '@'
    End: exit
    Start_For_Empty_Tell_Command: false
  Deep_Search: true
```
Seems to only work for me and no one else. We all have `chatcontrol.command.tell` enabled. Even when a deop myself and set my rank to the lowest rank, this feature still only works for me.

**Comment by kangarko** [comment]
I am on it!

**Comment by kangarko** [comment]
Apology for a late reply!

I have solved the issue where @testperson sends the literal output to the chat. The message is now lowercased and thus the name will never sent, solving the problem.

As for the sound notify, this appears to be unsolvable at the moment, so you'd have to change the prefix for either two so they won't collide.

**Comment by LogGits** [comment]
> I have solved the issue where @testperson sends the literal output to the chat. The message is now lowercased and thus the name will never sent, solving the problem.

That is awesome news!

> As for the sound notify, this appears to be unsolvable at the moment, so you'd have to change the prefix for either two so they won't collide.

My sound notify is setup like this:
```yaml
Sound_Notify:
  Enabled: true
  Cooldown: 2 seconds
  Require_Afk: false
  Require_Prefix: none
  Sound: ENTITY_EXPERIENCE_ORB_PICKUP, 100F, 1F
  Color: '&c'
  Enabled_In_Commands:
  - msg
  - tell
  - t
  - w
  - r
  Use_Sender_Group_Color: false
```
