### ISSUE TITLE
Suggestion: Trigger the point system with chat limit.

### ISSUE THREAD

**Issue by ZerekZarson** [kangarko/ChatControl-Pro#1295]
_Apologies in advance if I've just misunderstood the configuration process._

Within the points system:

`delay_points:` triggers when `Message_Delay: x` or `Command_delay: x` is exceeded.

`Similarity_Points` triggers when `Similar_Percentage_Block` meets it's requirements.

I was hoping to trigger the point system when a player reaches the limit of messages within x period
```
Anti_Spam:
    Chat:
        Limit:
            Period: x
            Max_Messages: x
```
This would give server administrators the ability to allow spam to that set `limit:` and then punish via the point system.

Maybe the limit should trigger `delay_points` as well or maybe it should trigger its own variable `limit_points`
