### ISSUE TITLE
Struggling to get a weight-ordered list of LuckPerm group prefixes.

### ISSUE THREAD

**Issue by malonnnn** [kangarko/ChatControl-Pro#1312]
I am trying to get a weight-ordered sorted list of prefixes for a player using LuckPerms. Using Vault's {pl_prefix} with multiprefixes set to true is very close to what I want, but I cant control the order.

So I tried using PlaceholderAPI with LuckPerms extension installed, but I still couldn't get what I wanted using {luckperms_prefix} as that only shows a single prefix.

Anyone got any ideas?

Prefixes and their priorities:
https://i.imgur.com/ZJ8bKMd.png

The player info and groups (all group weights match the prefix weight above. Example: council group has weight 40 and prefix priority of 40):
https://i.imgur.com/34b329k.png

How it looks when the player talks using {pl_prefix} and multiprefixes set to true:
https://i.imgur.com/9htUSVs.png

How it looks when the player talks using {luckperms_prefix}:
https://i.imgur.com/4c35aga.png

Channel formatting:
```
  Chat:
    First_Part:
      Message: "{world}&a&l/&r"
    Second_Part:
      Message: "{luckperms_prefix}&a&l/&r{pl_suffix}"
      Hover_Event:
        Action: SHOW_TEXT
        Values:
       - "{player}"
        - "&7Message issued: &b{timestamp}"
        - "&7Click to send a message"
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: '/msg {player} '
    Third_Part:
      Message: "{message}"
```
