### ISSUE TITLE
PlaceholderAPI and issue with variables

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#1319]
External related ticket: https://github.com/GeorgH93/MarriageMaster/issues/72
Spigot: 1.13.2
CC: 8.3.0
PAPI: 2.10.3
Edit: MarriageMaster recently updated and changed placeholders, it may have something to do with the issue.

Following placeholders in a SHOW_TEXT action in formatting.yml are not showing anything:
![imagen](https://user-images.githubusercontent.com/6623704/61996974-f0a04c00-b09a-11e9-8f8b-e4d999b45814.png)

The placeholders are from MarriageMaster: https://github.com/GeorgH93/MarriageMaster/wiki/Placeholders

Relevant config:
formatting.yml
```   
Player:
      Message: '{nick} '
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&8*-----* &f{player} &8*-----*'
        - '&7Rango/s&8: &f{pl_group}'
        - '&7Mundo: &f{world}'
        - '&7Pareja: {marriagemaster_heart} {marriagemaster_partner}'
```

It looks as though the tags simply didn't exist.
