### ISSUE TITLE
<center> tag has spaces

### ISSUE THREAD

**Issue by Bobcycle** [kangarko/ChatControl-Pro#1322]
Why do I get these annoying spaces in my messages when using the <center> tag?

```
Motd:
  Enabled: true
  Delay_Ticks: 2
  Command_Aliases:
  - motd
  - welcome
  Sound: ENTITY_FIREWORK_LAUNCH, 1F, 0.1F
  Message:
  - '&e'
  - '<center> &6Minevictus server'
  - '<center> &eWelcome back {player}, enjoy your stay and make'
  - '<center> &esure to check out the links below here!'
  - '&e'
  - '[JSON] ["",{"text":"                       x","color":"yellow"},{"text":" Wiki","color":"gold","clickEvent":{"action":"open_url","value":"https://minevict.us/wiki/"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click
    here","color":"yellow"}]}}},{"text":" x","color":"yellow"},{"text":" Discord","color":"aqua","clickEvent":{"action":"open_url","value":"https://discord.gg/ad9TYGH"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click
    here","color":"yellow"}]}}},{"text":" x","color":"yellow"},{"text":" Forum","color":"gold","clickEvent":{"action":"open_url","value":"https://minevict.us/forum/public/"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click
    here","color":"yellow"}]}}}]'
  - '[JSON] ["",{"text":"                             Quick survey","color":"red","clickEvent":{"action":"open_url","value":"https://forms.gle/66YYJT3MDuSngbAG6"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Click
    here","color":"yellow"}]}}}]'
  - '&e'
  Message_First_Time: []
```

![image](https://user-images.githubusercontent.com/43217357/62005214-32c79d00-b130-11e9-83fd-bb5718421423.png)
