### ISSUE TITLE
{server_name} placeholder

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl-Pro#1326]
The placeholder {server_name} ( formatting ) doesn't seem to be using the Server_Name provided in the config file.
ChatcontrolPro 8.3.6

**Comment by kangarko** [comment]
Where are you trying to use it? Just tested & works on the vanilla settings (https://i.imgur.com/6HQPeFd.png)

**Comment by AmazedMender16** [comment]
@kangarko Under 

```
  Private_Message_Receiver:
    Everything:
      Message: 'You have received a message from {sender}'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - 'Received {timestamp}'
        - 'Sender: {sender}'
        - 'Server: {server_name}'
```
