### ISSUE TITLE
Upgrading from v7 to v8, chat messages are not shown or logged in console

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#1343]
Instead of using our channel format in the console for server chat, all we see is the following:

[23:32:43 INFO]: Sending 'hiya'
[23:32:45 INFO]: Sending 'hey'
[23:32:51 INFO]: Sending 'what's up'
[23:32:56 INFO]: Sending 'nothing'
[23:32:59 INFO]: Sending 'oh lol'
[23:33:35 INFO]: Sending 'me too'
[23:33:52 INFO]: Sending 'want to go mining'
[23:33:59 INFO]: Sending 'sure'

There should be player names, server/channel prefix, etc.

Using ChatControlPro 8.3.6.  I also have DiscordSRV installed if that makes a difference.

One of our example channel configs from formatting.yml:

```
  testchannel:
    Bracket:
      Message: '&7[&1T&7]&f '
    Player:
      Message: '{pl_prefix}{nick}{pl_suffix}&7: &r'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&7Name&f: {player} {javascript_is_helper}{javascript_is_seniorhelper}{javascript_is_moderator}{javascript_is_admin}{javascript_is_owner}
          {javascript_is_vip}'
        - '&7Time Played&f: {statistic_time_played}'
        - '&9Click to PM&f {player}'
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: '/pm {player} '
    Msg:
      Message: '{message}'
```
