### ISSUE TITLE
DeathMessages

### ISSUE THREAD

**Issue by pvpstryker** [kangarko/ChatControl-Pro#1363]
Hey, I am using latest ChatControlPro,
There is 0 documentation regarding death messages in your GitHub, that's why I am here.
I am trying to make 3 categories of messages all regarding PVP. One will be dying to an unarmed enemy, one dying to an item in the enemy's hand and one dying to an arrow.

I tried pvp_fist, pvp_fists and pvp_unarmed, none work.
I have yet to find a condition that makes it so whenever the killer has an item in his hands.
And finally I have no clue the condition for a bow and arrow.

No condition is documented, so I have no clue how to configure this, can you help?

**Comment by c0wg0d** [comment]
I spent hours testing out the death messages.  There is documentation in the messages.yml file inside the JAR.  Download the JAR, rename it to .zip, unzip it, open up messages.yml.

You need to specify the item names like this:

```
      pvp_diamond_sword:
        Killer: PLAYER
        Killer_Item: DIAMOND_SWORD
        Message:
          - '&c{player} &7was distracted by {killer}&7''s shiny {killer_item}!'

      pvp_raw_fish:
        Killer: PLAYER
        Killer_Item: RAW_FISH
        Message:
          - '&c{player} &7was trout slapped by {killer}&7''s {killer_item}!'

      pvp_wood_sword:
        Killer: PLAYER
        #
        # You may use the wildcat '*' character to match any kind of sword. Careful, this is not regular expression, just our own system!
        #
        Killer_Item: '*_SWORD'
        Message:
          - '&c{player} &7got a splinter and died from &a{killer}&7''s {killer_item}!'

      pvp_wood_axe:
        Killer: PLAYER
        Killer_Item: '*_AXE'
        Message:
          - '&c{player} &7asked {killer}&7''s {killer_item} a terrible knock knock joke'

      pvp_x: # The _x is just for the plugin to recognize this as the last condition.
        Killer: PLAYER
        #
        # Message for the killer, if available:
        #
        Killer_Message:
          - '<noprefix> &8[&4PvP&8] &6You just &cmurdered &6{player}!'
          - '<noprefix> &8[&4PvP&8] &6You just &cslayed &6{player}!'

        Message:
          - '&c{player} &7was annoyed to death by &a{killer}&7!'
          - '&a{killer} &7has slain &c{player}&7!'
```
