### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Drakanoiderna** [kangarko/ChatControl-Pro#1395]
Hi 
In staff_message I did try adding more then one and wonder if it si possebel becosi cant get it to work. I wanted it so say some funny things on login and for staff more directed at that staff member. But only last one seam to work.

    staff_message:
      #
      # Permission player must have for messages below when they join.
      #
      Permission: "chatcontrol.joinmessage.player"
      Message:
        - '&8[&2+&8] &7Välkommen &b{player} &7till Midgardsaga!'
        - '&8[&2+&8] &7Bless &9{player} &7för att loga in!'
        - '&8[&2+&8] &7Säg hej till &e{player} &7!'
        - '&8[&2+&8] &7 &c{player} &7halka in på ett bananskal!'
    staff_message:
      Permission: "chatcontrol.joinmessage.staff.broken_arrow1"
      Message:
        - '&8[&2+&8] &7se upp &b{player} &7bryter era pilar!'
        - '&8[&2+&8] &7Se upp &9{player} &7kommer och tar erean redstone!'
        - '&8[&2+&8] &7shhhh &e{player} &7kommer!'
        - '&8[&2+&8] &7Admin online &e{player} &7kommer!'
      Permission: "chatcontrol.joinmessage.staff.isman_00"
      Message:
        - '&8[&2+&8] &7se upp &b{player} &7kommer nu blir det kallt!'
        - '&8[&2+&8] &7Se upp &9{player} &7kommer och tar era is block!'
        - '&8[&2+&8] &7shhhh &e{player} &7kommer!'
        - '&8[&2+&8] &7Admin online &e{player} &7kommer!'

**Comment by kangarko** [comment]
You can only have one key Permission and one key Message for the staff message. If you want to use it as do you right now, split it:

```
staff_message_1:
  Permission: "chatcontrol.joinmessage.staff.broken_arrow1"
  Message:
    - '&8[&2+&8] &7se upp &b{player} &7bryter era pilar!'
    - '&8[&2+&8] &7Se upp &9{player} &7kommer och tar erean redstone!'
    - '&8[&2+&8] &7shhhh &e{player} &7kommer!'
    - '&8[&2+&8] &7Admin online &e{player} &7kommer!'
staff_message_2:
  Permission: "chatcontrol.joinmessage.staff.isman_00"
  Message:
    - '&8[&2+&8] &7se upp &b{player} &7kommer nu blir det kallt!'
    - '&8[&2+&8] &7Se upp &9{player} &7kommer och tar era is block!'
    - '&8[&2+&8] &7shhhh &e{player} &7kommer!'
    - '&8[&2+&8] &7Admin online &e{player} &7kommer!'
```
