### ISSUE TITLE
notify colour

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1453]
Issue with colour formatting. Defaults text to white:

`&6Hey {playername} testing 123`

what i expect to see is:
`&6Hey &e&o{playername}&6 testing 123`
but instead i see:
`&6Hey &e&o{playername}&f testing 123`

Could you add a method that fixes this. It can be achieved by getting the colour of the text before playername.

Config:
```yaml
Sound_Notify:
  Enabled: true
  Cooldown: 2 seconds
  Require_Afk: false
  Require_Prefix: 'none'
  Sound: ENTITY_EXPERIENCE_ORB_PICKUP, 100F, 1F
  Color: '&e&o'
  Enabled_In_Commands:
  - msg
  - tell
  - t
  - w
  - r
```
Chatcontrol version: 8.4.7
Paper 1.14.4 - 225

**Comment by kangarko** [comment]
Hello,

this is a known issue. Currently there is no workaround. Since the chat API splits of chat message into different parts (https://www.spigotmc.org/wiki/the-chat-component-api/), we can only see the color of the last part, which appears to be white to ChatControl. The player's color appears to be located in his prefix. 

Lastly you can try melting all format parts together to see if that makes any difference, but I am not sure: https://i.imgur.com/JNELGnw.png

**Comment by LogGits** [comment]
Couldnt a work around be to apply the colourcode at the beginning of the next string. 
`e.g. &6Hi this is a test`
would turn into:
`e.g. &6Hi &6this &6is &6a &6test`

in doing so this wouldnt impact text like:
`&6Hi this is a &atest`

As it would apply the &6 at the beginning of the &a.
You can also utilise `ChatColor.getLastColors("");` to help achieve this.

Players have been bugging me about this, and large plugins like CMI, utilise a similar type of method to achieve mentions with colour persisting.

**Comment by kangarko** [comment]
Thanks. I reviewed the code but this is already being done in a semi-similar way as you shown.

![a](https://i.imgur.com/hykKXeV.png)

How are you setting the &6 color for players? Through formatting.yml?

**Comment by LogGits** [comment]
I wish mine was like that haha. So our config looks like this:
```
Formats:
  Chat:
    Prefix:
      Message: '&r{pl_prefix}'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&8*-----* &f{player} &8*-----*'
        - '&aPrefix&8: &7{pl_prefix}'
    Player:
      Message: '{player}&f:'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&6Username: &f{player}'
        - '&7Click to send a PM'
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: '/msg {player} '
    The_Rest:
      Message: '{pl_suffix} {message}'
```
