### ISSUE TITLE
Condition comparison broken?

### ISSUE THREAD

**Issue by PsychoLynx** [kangarko/ChatControl-Pro#1457]
Hello!

We are using ChatControl Pro 8.4.8 (latest version) for our death message control. We have a custom JavaScript variable called "killername", which returns the displayname of the killer.  We use this primarily with MythicMobs.

In JavaScript.txt, the variable is defined as follows:

```
 define {killername}
 script:
   player.getLastDamageCause().getDamager().getCustomName();
```

On messages.yml we have the following set up.

```
      direwolf:
        Condition: '"{killername}" == "Direwolf"'
        Message:
        - '[Debug] Killername: {killername}'
```

However, it seems no matter what we do, we cannot get the comparison to work like this. Strangely enough, if we set 

`Condition: '"{killername}" == "{killername}"'`

Then the comparison works, and the message that is returned is "[Debug] Killername: Direwolf".
Am I doing something wrong here or is there a bug in the comparison system? We are not using any color codes or the like in the names.

It also seems to not work when setting '"{player}" == "PsychoLynx"'`, which implies to me that there might be a bug in the system?

Thank you in advance for the help.
