### ISSUE TITLE
Limiting certain commands, not all

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1458]
I would like to limit the use of certain commands like `/tpa` requests.

The section for this would be:
```
  Commands:
  
    # How many seconds the player must wait till their next command? Set to 0 to disable.
    Command_Delay: 0
    
    # Limit how many messages the player can send within a certain time frame.
    Limit: 
      Period: 120 seconds
      # By default they can send up to five messages within a ten seconds period.
      Max_Commands: 3
```
But by doing this all commands are limited to this time frame. To my understanding the whitelists defined after this section do not support this Max_Commands.

How can I only restrict certain commands?
