### ISSUE TITLE
Autostart msg via /msg & /tell, not working

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1481]
```
  Auto_Start:
    Enabled: true
    Prefix: '@'
    End: exit
    Start_For_Empty_Tell_Command: true
```
`Start_For_Empty_Tell_Command: true` doesn't work. When **Player1** on the same server typing `/msg player2` it sends **player2** an empty msg. Then when Player1 goes to type in chat, it doesnt go through /msg. (the same thing applies to when a player types `/tell` instead of `/msg`.

Chc ver - 8.4.11
paper 1.14.4 build 236
