### ISSUE TITLE
Bungee chat not broadcasted in console?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1496]
Hey,

I have 3 servers, Survival / Creative / Lobby. They are all using the bungee chat (global chat)
But the messages only show up in the console of Survival (since that's where they mostly message)
Sometimes a message randomly shows up in the console of the others, but most of the times it doesn't.

What could this be?

**Comment by lackoSK** [comment]
Have you followed the tutorial for the bungeecord and installed BungeeControl well?

**Comment by Sikatsu** [comment]
Yes, I have. In-game it works fine, but it's not really being broadcasted to the other consoles.

**Comment by lackoSK** [comment]
What do you mean by broadcasting to other consoles? Not sure. Use:
```

# -------------------------------------------------------------------------------------------------
# Announce important messages with the "/chc announce" command.
# You can customize the format in localization.
#
# TIP: Use {receiver} variable in the message to replace it to each player's name!
# -------------------------------------------------------------------------------------------------
Announcer:
  Bungee: true
  Ignore_Self: false
  Log_To_Console: true
```
