### ISSUE TITLE
ChatControl Pro prevents EmojiChat replacement from working.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1498]
RE: https://github.com/RadBuilder/EmojiChat/issues/10

ChatControlPro 8.5.0-BETA
EmojiChat 1.8.3
Paper dev 32 (Spigot 1.15.1)

@kangarko Wasn't sure whether or not to report this as a ChatControl Pro issue, but seeing as how it works with ChatControl commands / chat channels, but not public chat, I think it's a CC issue?

ChatControlPro prevents EmojiChat from replacing shortcuts and characters as emojis in public chat.
https://www.spigotmc.org/resources/emojichat.50955/

I can use emojis in ChatControlPro command channels such as the staff / admin chat. I can also see emojis in ``/me` and ``/msg``. Just in public chat, emojis do not appear. 

Formatting
```
Formats:
  Chat:
    Default:
      Message: '&7{javascript_prefix} '
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&f&lName:&r {player}'
        - '{javascript_tag}'
        - '&e{javascript_description}'
      Sender_Permission: chatcontrol.groups.default
    Player:
      Message: '{display_name}&f: '
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '{player}'
    The_Rest:
      Message: '{message}'
```

I have tried setting the listener priority for formatter to NORMAL, HIGH, and HIGHEST.
```
Listener_Priority:
  Checker: NORMAL
  Formatter: HIGHEST
  Signs: HIGHEST
```
