### ISSUE TITLE
Spam First Join Messages Added?

### ISSUE THREAD

**Issue by jakkuh** [kangarko/ChatControl-Pro#1540]
https://i.imgur.com/WrXEUJG.png

I just updated ChatControl to 8.5.7 and now it seems to have started messaging when players join for the first time w/o any config option to disable this. Can you please fix this its really annoying!

**Comment by jakkuh** [comment]
Side note: seems to also happen on first quit from the server for each user.

**Comment by jakkuh** [comment]
Okay have determined this is a BungeeControl feature as per it's latest update.

When you add functionality like this in the future, please don't enable it by default!

```
global-join:
  enabled: false
  message:
  - '&8[&d>&8] &e{player} &fhas joined for first time!'
```
