### ISSUE TITLE
Formatting Conditions not working as expected

### ISSUE THREAD

**Issue by Tina-King** [kangarko/ChatControl-Pro#1542]
**Explanation**
This stopped working on 1.15.2 version:
`Condition: '!player.hasPermission("minestar.nonplayer")'`

Right now, everyone is passing the condition meaning they get the message part.

Basically, everyone with the `minestar.nonplayer` permission should not be able to have their skyblock island level as a prefix in chat, but currently people with the permission are still getting skyblock level in chat.

**Version**
This worked fine until I updated to 1.15.2 and then got 8.5.7.

**Permissions System**
I use Luckperms permission system.

**The formatting config**
```YML 
 Chat:
    BSkyBlock_Part: 
      Message: "&7[Lvl. &3{level_bskyblock_island_level}&7] &r"
      Condition: '!player.hasPermission("minestar.nonplayer")'
```
