### ISSUE TITLE
Players send and receive repeated PMs

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#156]
I updated from 7.1.3 to 7.1.5 on all my Spigot servers and now whenever someone sends a PM, they see it multiple times in chat.  The same happens on the receiver end.  This was not a problem before upgrading and I did not modify any configurations or permissions.

Players have permissions chatcontrol.commands.reply: true and chatcontrol.commands.tell: true.

My chat.yml has the following format:

```
Private_Message_Sender:
    Parts:

      Everything:
        Message: "&7[&6me&7->&f{player}&7]:&o {message}"
        Hover_Event:
          Action: SHOW_TEXT
          Values:
            - '&7Name&f: {player} {javascript_is_helper}{javascript_is_seniorhelper}{javascript_is_moderator}{javascript_is_admin}{javascript_is_owner} {javascript_is_vip}'
            - '&9Click to PM&f {player}'
        Click_Event:
          Action: SUGGEST_COMMAND
          Value: "/tell {player} "

  Private_Message_Receiver:
    Parts:

      Everything:
        Message: "&7[&f{player}&7->&6me&7]:&o {message}"
        Hover_Event:
          Action: SHOW_TEXT
          Values:
            - '&7Name&f: {player} {javascript_is_helper}{javascript_is_seniorhelper}{javascript_is_moderator}{javascript_is_admin}{javascript_is_owner} {javascript_is_vip}'
            - '&9Click to PM&f {player}'
        Click_Event:
          Action: SUGGEST_COMMAND
          Value: "/pm {player} "
```

In my settings.yml, I have the following for private messages:

```
Private_Messages:
  Enabled: true
  Bungee: true
  Aliases:
    Tell:
    - msg
    - pm
    - t
    - w
    - whisper
    Reply:
    - r
  Static_Format_Sender: '&8[&6you &8-> &6{player}&8] &7{message}'
  Static_Format_Receiver: '&8[&6{player} &8-> &6you&8] &7{message}'
  Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver
```
