### ISSUE TITLE
Creeper Death Messages do not work

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#160]
I have been trying out the custom death messages in ChatControlPro and they are awesome!  I have found that this following does not work for people that die from creeper explosions:

```
Entity_Explosion:
    Message: '&e{player} &7blew up'

    Conditions:
      creeper:
        Killer: CREEPER
        Message: # doesn't work
          - '&e{player} &7was the victim of a creeper ambush'
          - '&e{player} &7believed creepers were the hugging type'
          - '&e{player} &7thought that creeper was a bush'
          - '&e{player} &7didn''t know walking TNT could be so well camoflauged'
          - '&e{player} &7tried to hug a creeper'
          - '&e{player} &7tried to befriend a creeper'
          - '&e{player} &7should listen more carefully for &2creepers&f next time'
          - '&7Oh my gosh &e{player}, look at that guy. He is so creepy! But I hear he''s the bomb!'
          - '&7A creeper blast vaporized &e{player}'

```

The message is always "player blew up" and never any of the custom conditions.  If I remove the first "Message" node, then the plugin loads the value from the default config (something like "player died from an entity explosion").

I'm using the latest build of Spigot 1.11.2.  Most of the other death messages work, but this one for creepers does not.
