### ISSUE TITLE
Formatting question

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1606]
For the formatting.yml file:
I want to show marriage status in this:
```
    Player:
      Message: '{player}:'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - ''
        - '&eMarriage: {marriagemaster_partner}'
        - '&eBal: ${custom_balance}'
        - '&7Click to send a tp'
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: '/tpa {player} '
```
whereby the marriage status is only displayed if they are actually married. There is a {marriagemaster_ismarried} placeholder that returns the state. Just unsure how to show marriage status only when they are married but keep all other data there.
(id also love to use this to display a custom hover msg depending on permission)

Is this all possible, if so letme know. Cheers 🙂
