### ISSUE TITLE
Getting 2 quit messages, 1 from ChatControl and 1 from default Minecraft

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#1621]
I have a very strange issue that I haven't been able to figure out yet.  I'm using ChatControl 8.6.6 across all my servers on a BungeeCord network.  Every server uses the exact same messages.yml configuration, which has the following section:

```
Quit_Message:
  Enabled: true
  Ignore_Vanished: true
  Message: default
  Conditions:
    hide_quit_message:
      Permission: chatcontrol.hidequitmessage
      Message: none
```

When a player leaves the game, it shows the ChatControl leave text, and then 10 seconds later, it shows the default Minecraft leave text (note the lack of a period in the second message, which is the Minecraft default):

[02:55:42 INFO]: playername left the game.
[02:55:52 INFO]: playername left the game

I have many servers, and this only happens on one of them.  What would be causing this?
