### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Steev93** [kangarko/ChatControl-Pro#1631]
Everything works well with Discord as I already had it picking up players chat,

However, I need it to work with the custom death messages

http://prntscr.com/s1i897

As seen here... I don't want it to display the player's name for the death message but show it as an actual death message how would I do this? It doesn't display the player's name in-game.

**Comment by lackoSK** [comment]
Hello,

Replied to you on discord

Sincerely,
Ladislav from MineAcademy.org

**Comment by Steev93** [comment]
@lackoSK  
Okay sorry i'll explain it this way
```
# -----------------------------------------------------------------------------------------
# Configure custom death messages.
#
# Thanks to c0wg0d for contributions and examples.
# -----------------------------------------------------------------------------------------
Death_Messages:
  #
  # Set to true to enable custom death messages.
  #
  Enabled: true
  #
  # The prefix used in front of all messages.
  #
  Prefix: ':skull:'
  #
  # Do not send the message if the player is vanished? Most vanish plugins are supported.
  #
  Ignore_Vanished: true
  #
  # Enable to make messages compatible with DiscordSRV / DynMap or similar.
  #
  Hide_By_Gamerule: true
  #
  # Log death messages to console?
  #
  Log_To_Console: true
  #
  # Integration with DiscordSRV.
  #
  Discord:
    #
    # Send death messages to a Discord channel?
    #
    Enabled: true
    #
    # Channel name on Discord where to send.
    #
    Channel: 'global'
  #
  # Here you can customize the {killer} and {killer_item} variable's translations.
  #
  Translate:
    Skeleton: Mighty Skeleton
    Wither Skeleton: Withered Skeleton
    Diamond Sword: Sword of Death
```

Yet it displays like this in the Discord Chat...
http://prntscr.com/s1pie0

Hoping for it to display like this? 
http://prntscr.com/s1pixd
(which is what DiscordSRV is showing)

Or would i need to broadcast !the death?
