### ISSUE TITLE
Anti Caps for Item2Chat

### ISSUE THREAD

**Issue by AngelDeaD** [kangarko/ChatControl-Pro#1639]
I have Item2Chat plugin. It works great for people who have lowered case nicknames, but for those who have upper case nickname it says "Please do not use so much CAPS!"

Chc version: 8.6.2

AntiCaps section in settings.yml

```
Anti_Caps:
  Enabled: true
  Enabled_In_Commands: false
  Commands_To_Apply:
  - /tell
  - /msg
  - /m
  - /pm
  - /t
  - /w
  - /r
  - /reply
  Points:
    Warn_Set: spam
    Amount: 4 * ({capsPercentage} / 2)
  Ignore_Usernames: true
  Min_Message_Length: 5
  Min_Caps_Percentage: 50
  Min_Caps_In_A_Row: 5
  Whitelist:
  - OMG
  - LOL
  - WTF
  - WOW
  - ROFL
  Warn_If_Caps_Above_Percent: 50
```

Item2chat uses this format:
`[item]{player_name}`

My `ignore_usernames` was false, I chaged it to true (did `chc reload`), but I still have the problem. I also tried to whitelist it:
`'[item]{player}'`
`'[item]{nick}'` 
but no change. I guess `{player}` and `{nick}` do not resolve to nickname of player in AntiCaps section. Even though, they are supported: https://github.com/kangarko/ChatControl-Pro/wiki/Variables
