### ISSUE TITLE
[Bug] Custom leave messages

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl-Pro#1667]
```
Hide_Join_Quit_Kick_Messages: false
Join_Message:
  Enabled: true
  Message: '&7[&e{server_time_HH:mm:ss}&7] &e« &f{player} &e» &acsatlakozott a szerverhez!'
#  Conditions:
#    hells_message:
#      Gamemode: SURVIVAl
#      World:
#      - world_nether
#      - hardcore_nether
#      - another_nether
#      Message: none
#    staff_message:
#      Permission: chatcontrol.joinmessage.staff
#      Message: '&7[&e{server_time_HH:mm:ss}&7] &e« &f{player} &e» &acsatlakozott a szerverhez!'
#    jubileum_message:
#      Condition: player.getStatistic(Java.type("org.bukkit.Statistic").LEAVE_GAME) == 99
#      Message:
#      - none
  Ignore_Vanished: true
  Delay_Ticks: 1
Quit_Message:
  Enabled: true
  Message: '&7[&e{server_time_HH:mm:ss}&7] &e« &f{player} &e» &ckilépett a szerverről!'
#  Conditions:
#    staff_message:
#      Permission: chatcontrol.joinmessage.staff
#      Message: '&7[&e{server_time_HH:mm:ss}&7] &e« &f{player} &e» &ckilépett a szerverről!'
  Ignore_Vanished: true
Kick_Message:
  Enabled: true
  Message: '&7[&e{server_time_HH:mm:ss}&7] &e« &f{player} &e» &ckidobva a szerverről!'
```
Sometimes it says i have been kicked from the server when left :-|
but Quit_Messages aren't work for anyone :(
