### ISSUE TITLE
1.15.2: /tell still works if muted with /mute

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#1681]
As the title says, if you are muted with /mute, you can still use /tell.
I'm unsure about what mute is being executed though, if essentials's, chatcontrol's, or advancedban's
```
Mute:
  Broadcast: true
  Prevent:
    Writing_Books: false
    Placing_Signs: true
  Silence:
    Join_Messages: true
    Quit_Messages: true
    Death_Messages: true
  Disabled_Commands:
  - /me
  - /tell
  - /msg
  - /r
  - /w
  Apply_Limits_For_Essentials_Mute: true
```
If I had to guess, I'd say it's just a compatibility problem with AdvancedBan's mute, which is probably the highest priority.

I thought I might just use essentials's mute, but they don't offer tempmute like AdvancedBan. So all I can do is ask for advancedban compatibility, if it truly is the issue.
