### ISSUE TITLE
1.15.2: ChatControl 9.0.0 - data.json still being written to despite mysql being enabled.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1698]
Paper dev 348 (Spigot 1.15.2)
Waterfall dev 346 (BungeeCord)
ChatControl-Pro v9.0.0
BungeeControl v3.0.0
DiscordSRV 1.19.1-SNAPSHOT-1591793461

The data.json file is still writing information such as;

```
{"Players": {
   "291c2d6e-a25d-4179-a11e-3011f9a97b2b": {
      "Chat_Mode": "BUNGEE",
      "Last_Active": 1591886902715
   },
   "24b95709-012c-4dee-a324-c37ff1a4e56c": {
      "Chat_Mode": "BUNGEE",
      "Last_Active": 1591886901500
   },
   "72c34e55-b89a-49b4-9db0-0a1c8a1a0675": {
      "Chat_Mode": "BUNGEE",
      "Last_Active": 1591887586392
   },
   "cc8185c2-c420-4a5d-a4d2-846d72c94173": {
      "Chat_Mode": "BUNGEE",
      "Last_Active": 1591886902187
   },
   "4f545dd1-e0c2-495e-994d-068564662bff": {
      "Chat_Mode": "BUNGEE",
      "Last_Active": 1591887182987
   },
   "779abe83-c33d-4c3a-b27d-5438509e53ad": {
      "Chat_Mode": "BUNGEE",
      "Last_Active": 1591887082699
   },
   "53774a66-2a76-4be2-aca3-17812157d198": {
      "Chat_Mode": "BUNGEE",
      "Last_Active": 1591886902185
   }
}}
```

Despite mysql being enabled in the primary settings.yml.

```
# -----------------------------------------------------------------------------------------------------
# MySQL connection allows to store same information over multiple servers.
# -----------------------------------------------------------------------------------------------------
MySQL:
  #
  # Save players' data to the database when they exit the server and load them on join?
  #
  Enabled: true
  #
  # The host and the port to connect to
  #
  Host: 'localhost:3306'
  #
  # The database name
  #
  Database: 'chatcontrol'
  #
  # The username
  #
  User: 'chatcontrol'
  #
  # The password
  #
  Password: 'censored'
```
