### ISSUE TITLE
1.15.2: ChatControl 9.0.0 - Discord toggle does not function and is formatting discord messages improperly.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1700]
Paper dev 348 (Spigot 1.15.2)
Waterfall dev 346 (BungeeCord)
ChatControl-Pro v9.0.0
BungeeControl v3.0.0
DiscordSRV 1.19.1-SNAPSHOT-1591793461

ChatControl is not respecting the discord ``enabled: false`` toggle in settings.yml. It is still formatting discord messages upstream (minecraft -> discord) and downstream (discord -> minecraft) and doing it improperly.

* User typed in discord channel.
![link](https://i.imgur.com/pPC4W96.png)
* How it showed up in-game.
![link2](https://i.imgur.com/l39Y56P.png)

---

* I typed in-game in public chat as an admin.
![link3](https://i.imgur.com/9UjzeVa.png)
* How it showed up on discord.
![link4](https://i.imgur.com/Odqd7Kg.png)

Similarly, staff-chat formats incorrectly when sending upstream to discord.
* I typed in-game in staff chat as an admin.
![link5](https://i.imgur.com/fatGmr7.png)
* How it showed up on discord.
![link6](https://i.imgur.com/zvzZBuT.png)

I do not want ChatControl to add formatting to messages sent upstream or downstream. It seems to use the chat.yml/bungee_chat.yml formatting for players who type _from_ discord to _in-game_. Likewise, admin_chat formatting seems to be shared both ways when I only want to format staff-chat in-game and relay simple messages to the staff channel.

Everything displays fine in-game and on discord with DiscordSRV & ChatControl v8.6.6. With the exception I have to use Discord-Staff-Chat on v8 since ChatControl relayed staff messages to multiple discord channels, but was generally formatted fine.

---

**ChatControl formats/discord.yml**
```
Composition:
- Part: '&8<&7Discord&8> &7{player}: &f'
```

**ChatControl formats/admin_chat.yml**
```
Composition:
- Part: '&4[Staff]&7 &r{display_name}&f: '
  Hover:
  - '&7Click to reply.'
  Suggest_Command: '/ac '
- Part: '{message}'

```

**ChatControl formats/chat.yml**
```
Composition:
- Part: '&7{javascript_prefix} '
  Hover:
  - '&f&lName:&r {player}'
  - '{javascript_tag}'
  - '&e{javascript_description}'
- Part: '{display_name}&f: '
  Hover:
  - '{player}'
- Part: '{message}'

```

**ChatControl formats/bungee_chat.yml**
```
Composition:
- Part: '&7{javascript_prefix} '
  Hover:
  - '&f&lName:&r {player}'
  - '{javascript_tag}'
  - '&e{javascript_description}'
- Part: '{display_name}&f: '
  Hover:
  - '{player}'
- Part: '{message}'
```

**ChatControl settings.yml**
```
Chat_Formatting:
  #
  # Enable chat formatting?
  #
  Enabled: true
  #
  # The default chat format applied over all worlds.
  #
  Format_Default: chat
  #
  # A format used in the /me command.
  #
  Format_Me: me
  #
  # Used in private messages for the sender
  #
  Format_PM_Sender: pm_sender
  #
  # Used in private messages for the recipient
  #
  Format_PM_Recipient: pm_recipient
  #
  # Used in admin chat via "/chc ach" command, used by staff to communicate with each other.
  #
  Format_Admin: admin_chat
  #
  # Used in "/chc bungeechat" command which sends messages over bungee.
  #
  # Requires BungeeCord support.
  #
  Format_Bungee: bungee_chat
  #
  # The default formatting of the message incoming from your Discord
  #
  # You can override this by setting the Discord_Format in individual channel settings
  #
  Format_Discord: discord
  #
  # What message should be displayed to the player on login? For settings visit messages.yml
  #
  Format_Motd: motd
  #
  # This message is sent when a player joins for the first time.
  #
  Format_Motd_First_Time: motd
  #
  # This message is sent when a player played under a specified threshold on the server.
  # See Newcomer.Threshold section here.
  #
  Format_Motd_Newcomer: motd
```
```
Integration:
  Discord:
    #
    # Send messages from your chat to your Discord and process incoming messages as chat messages
    #
    Enabled: false
    #
    # If you have chat formatting enabled, what channel on DiscordSRV should we sent
    # messages into? If you have channels enabled, see Chat_Channels below.
    #
    Chat_Channel: "global"
    #
    # What DiscordSRV channel should we send Admin_Chat into?
    #
    Admin_Chat_Channel: "staff-chat"
    #
    # What DiscordSRV channel should we send Bungee_Chat into?
    #
    Bungee_Chat_Channel: "global"
    #
    # What chat channels should we map when sending/receiving a message to/from Discord?
    #
    Connected_Channels:
      #
      # When you chat in the following Minecraft channels, their messages will go to the specified
      # Discord channels below. Channels unmapped will not be synchronized.
      #
      From_ChatControl:
        standard: "minecraft"
      #
      # When you chat in the following Discord channels, their messages will go to the specified
      # ChatControl channels below. Channels unmapped will not be synchronized.
      #
      From_Discord:
        minecraft: "standard"
```

**DiscordSRV config.yml** primary message forwarding settings
```
RespectChatPlugins: true
DiscordChatChannelDiscordToMinecraft: true
DiscordChatChannelMinecraftToDiscord: true
DiscordChatChannelBroadcastDiscordMessagesToConsole: true
```
**DiscordSRV message.yml** formatting
```
DiscordToMinecraftChatMessageFormat: "&8<&7Discord&8> &7%username%&f: %message%"
DiscordToMinecraftChatMessageFormatNoRole: "&8<&7Discord&8> &7%username%&f: %message%"
DiscordToMinecraftAllRolesSeparator: " | "

MinecraftChatToDiscordMessageFormat: "[%server_time_h%:%server_time_mm% %server_time_a%] **%javascript_prefix%** %displayname% &f» %message%"
MinecraftChatToDiscordMessageFormatNoPrimaryGroup: "%displayname% &f» %message%"
```

**Comment by lackoSK** [comment]
Hello,

Thank you for such a detailed report!

I've fixed both issues. For the second one, there will be a flag in config [disabled by default] 
![image](https://user-images.githubusercontent.com/53174757/84422931-06b8eb80-ac1e-11ea-8524-61029eee41f7.png)

PS: Hadn't time to test them properly, please test them. Thank you. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by IIIVVIII** [comment]
same problem. CC 9.0.0 beta1
![image](https://user-images.githubusercontent.com/34328781/84570434-f1bb9400-ada6-11ea-83bd-dcd5edb1343a.png)
Discord Integration - true or false - does nothing change at all.
Discord add formatting -  - true or false - does nothing change at all.
![image](https://user-images.githubusercontent.com/34328781/84570483-419a5b00-ada7-11ea-8753-daa4cd7a9c7e.png)

**Comment by lackoSK** [comment]
I've added debug: 

In settings.yml you will go to Debug: and set it to [discord-fm] 
Then, send us the output

PS: Available BETA-2

**Comment by IIIVVIII** [comment]
Beta-2 ? Where? It,s available to download??

**Comment by lackoSK** [comment]
just wait I will release it soon

**Comment by IIIVVIII** [comment]
> I've added debug:
> 
> In settings.yml you will go to Debug: and set it to [discord-fm]
> Then, send us the output
> 
> PS: Available BETA-2

nothing change for me. "discord" toggle and "Add format" toggle doesn't work in Beta1 with
[discord-fm] in config.

![image](https://user-images.githubusercontent.com/34328781/84575267-4bcb5200-adc5-11ea-97a5-93a6ad65e09f.png)


really looking forward to beta 2

**Comment by lackoSK** [comment]
Hello,

Can you send over the debug from beta2? Thank you

Sincerely,
Ladislav from MineAcademy.org

**Comment by IIIVVIII** [comment]
#1711

**Comment by mibby** [comment]
ChatControl Pro v9.0.0-BETA-3

Chat sent on discord is still being formatted incorrectly when sent in-game. It is **not** using the formats/discord.yml , but instead the chat/bungee_chat.yml format.

**Wrote on discord.**
![link-0](https://i.imgur.com/VHbzgvZ.png)
**What was displayed in-game.**
![link-1](https://i.imgur.com/dnWZcfw.png)

ChatControl settings.yml
```
Chat_Formatting:
  Enabled: true
  Enable_Variables: false
  Format_Default: chat
  Format_Bungee: bungee_chat
  Format_Discord: discord
```
```
Integration:
  Discord:
    Enabled: true
    Add_Formatting: false
    Replace_Emojis_With_Raw: false
    Chat_Channel: "global"
    Admin_Chat_Channel: "staff-chat"
    Bungee_Chat_Channel: "global"
    Connected_Channels:
      From_ChatControl:
        standard: "minecraft"
      From_Discord:
        minecraft: "standard"
```

formats/discord.yml
```
Composition:
- Part: '&8<&7Discord&8> &7{player}: &f'
```
