### ISSUE TITLE
Send a message to staff on player login/logout

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#1712]
Hey, I'd like only my staff to get notified (through permission) of players logging in or out.
Can I achieve this with CC? If so, how?

**Comment by lackoSK** [comment]
Hello,

What do you mean? They can already see the join message in chat?

Sincerely,
Ladislav from MineAcademy.org

**Comment by MithrandirCraft** [comment]
I mean only certain players (staff). Through a permission.

**Comment by lackoSK** [comment]
Hello,

This should be possible within a format. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by MithrandirCraft** [comment]
> should be possible within a format
what?

You mean formatting.yml?
If so, may I know what options could help me exactly?

**Comment by lackoSK** [comment]
Hello,

Just set the message to format name (eg. Join_Message)

Create format named Join_Message and use Receiver_Permission to send the message only to admins. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by MithrandirCraft** [comment]
How's this?
Formatting.yml
```
  Formats:
    Join_Message:
      Everything:
        Message: '&5{player} Entra.'
        Receiver_Permission: "ChatControl.Notify.PlayerLeft"
    Leave_Message:
      Everything:  
        Message: '&5{player} Sale.'
        Receiver_Permission: "ChatControl.Notify.PlayerJoined"
```
I guess I'll find out once I restart.

**Comment by MithrandirCraft** [comment]
Hm no, this doesn't seem to be working. No errors on plugin start though.

**Comment by lackoSK** [comment]
Hello,

Please take a look here https://github.com/kangarko/ChatControl-Pro/wiki/Formats

Sincerely,
Ladislav from MineAcademy.org

**Comment by MithrandirCraft** [comment]
> 
> 
> Hello,
> 
> Please take a look here https://github.com/kangarko/ChatControl-Pro/wiki/Formats
> 
> Sincerely,
> Ladislav from MineAcademy.org

Yeah, reading this tutorial is the first thing I did.
For starters there's nothing on ```Receiver_Permission``` written there. But I'm asuming it's valid, since you told me to use it.
Secondly, my shown syntaxes seem ok, it just needs to know when to show the message. So I thought maybe adding a condition would be the closest thing for this purpose. But on reading the conditions area, even if using javascript, idk how I would figure out when a player has logged out, furthermore even knowing the name of that player and displaying it in my message.

Do you understand what I'm asking for, and what my roadblock is? Do you understand why I'm asking? :'D

**Comment by MithrandirCraft** [comment]
I took a look at it. Aparently these formats can be used anywhere in the plugin?
I could add my formats to messages.yml join and quit messages, but I see no documentation on messages.yml on the wiki. I tried this:
```Join_Message:
  Enabled: true
  Message: Join_Message
  Ignore_Vanished: true
Quit_Message:
  Enabled: true
  Message: Leave_Message
  Ignore_Vanished: true```

**Comment by MithrandirCraft** [comment]
I currently have it set up like this, and it works, but everyone seems to be capable of seeing the message, even without the permission

messages.yml
```
Join_Message:
  Enabled: true
  Message: Join_Message
  Ignore_Vanished: true
  Permission: chatcontrol.notify.playerjoined
Quit_Message:
  Enabled: true
  Message: Leave_Message
  Ignore_Vanished: true
  Permission: chatcontrol.notify.playerleft
```` 
formatting.yml
```
  Join_Message:
    Everything:
      Message: '&5{player} Entra.'
  Leave_Message:
    Everything:  
      Message: '&5{player} Sale.'
```
