### ISSUE TITLE
Killer_Item section in Death_Messages seems inconsistent

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#172]
I am trying out the new Killer_Item option added to the Death_Messages section in 7.1.7 and running into some issues.

I don't know if it's a misconfiguration on my part or what.  Some guidance on how this works would be very helpful.  Below is a snippet of my config.  The problem is that it works on regular kills and the wood sword, but none of the others.  If I move the blocks of code around (like move the diamond_sword section above the pvp section), I can get different messages to show up, but it never seems to enable all of them at once.

```
  Entity_Attack
      pvp:
        Killer: PLAYER

        Message:
          - '&c{player} &7was annoyed to death by &a{killer}&7!'
          - '&a{killer} &7has slain &c{player}&7!'
          - '&a{killer} &7is victorious over &c{player}&7!'
          - '&a{killer} &7has overpowered &c{player} &7in combat!'
          - '&a{killer} &7killed &c{player}&7!'
          - '&a{killer} &7has ended poor &c{player}&7!'
          - '&a{killer} &7overcame &c{player} &7in battle!'
          - '&a{killer} &7defeated &c{player} &7in mighty struggle!'
          - '&a{killer} &7ended all dreams for &c{player}&7!'

      diamond_sword:
        Killer: PLAYER
        Killer_Item: DIAMOND_SWORD
        Message:
          - '&c{player} &7was distracted by {killer}&7''s shiny {killer_item}!'

      raw_fish:
        Killer: PLAYER
        Killer_Item: RAW_FISH
        Message:
          - '&c{player} &7was trout slapped by {killer}&7''s {killer_item}!'

      wood_sword:
        Killer: PLAYER
        Killer_Item: WOOD_SWORD
        Message:
          - '&c{player} &7got a splinter and died from &a{killer}&7''s {killer_item}!'

      wood_axe:
        Killer: PLAYER
        Killer_Item: WOOD_AXE
        Message:
          - '&c{player} &7asked {killer}&7''s {killer_item} a terrible knock knock joke'
```
