### ISSUE TITLE
1.15.2: Discord enable:false flag is not being honored and ChatControl is formatting messages

### ISSUE THREAD

**Issue by oranges13** [kangarko/ChatControl-Pro#1727]
We are using DiscordSRV 1.19.0 & ChatControl PRO 9.0.1-Beta

Current situation -- with ChatControl 9.0.0 Beta 4, Discord -> Minecraft chat was being hooked and no formatting was being used at all. Upgrading to Chatcontrol 9.0.1 Beta added discord formatting but my issue is that both formatting and discord integration are *disabled* in my configs. I would like DiscordSRV to handle the formatting and messaging and leave ChatControl out of it completely.

The `Enable: false` flag in both cases is not being honored.

```yml
`settings.yml`
Chat_Formatting:
  Enabled: false
  Enable_Variables: true
  Format_Default: chat
  Format_Me: me
  Format_PM_Sender: pm_sender
  Format_PM_Recipient: pm_recipient
  Format_Admin: admin_chat
  Format_Bungee: bungee_chat
  Format_Discord: discord
  Format_Motd: motd
  Format_Motd_First_Time: motd
  Format_Motd_Newcomer: motd
```
```yml
Integration:
  AuthMe:
    Hide_Quit_Message_If_Not_Logged: true
  Towny_Chat:
    Ignored_Channels:
    - '*'
  ProtocolLib:
    Replace_Unicode_In_Books: true
  Discord:
    Enabled: false
    Add_Formatting: false
    Replace_Emojis_With_Raw: true
    Chat_Channel: global
    Admin_Chat_Channel: ''
    Bungee_Chat_Channel: ''
    Connected_Channels:
      From_ChatControl:
        standard: minecraft
      From_Discord:
        minecraft: standard
    Apply_Format_To_Bungee_Chat: false
    Rules:
      Rules_Chat_Channel: rules
      Mention_Roles: []
      Delete_Mention: true
```

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4810800/ChatControl.zip)
