### ISSUE TITLE
1.15.2: ChatControl 9.0.1-BETA - Messages are not sent through BungeeCord if players are missing the permission chatcontrol.command.bungeechat

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1730]
Paper dev 367 (Spigot 1.15.2)
Waterfall dev 348 (BungeeCord)
ChatControl-Pro v9.0.1-BETA
BungeeControl v3.0.0
DiscordSRV 1.19.1-SNAPSHOT-1592862790.

Follow-up investigation of oddity reported here: https://github.com/kangarko/ChatControl-Pro/issues/1700#issuecomment-647847862

If players are missing the permission ``chatcontrol.command.bungeechat``, their message is not sent through BungeeCord and doesn't use the BungeeChat formatting. This is despite having BungeeChat enabled by default and toggling disabled.

```
Bungee_Chat:
  #
  # Enable bungee chat for players after login automatically. They can turn it off with '/chc bc switch'
  #
  Enabled_By_Default: true
  #
  # Should we send the messages to console?
  #
  Log_To_Console: true
  #
  # Write to logs/bungee-chat.txt ?
  #
  Write_To_File: true
  #	
  # Should we allow players to toggle BungeeChat?	
  #	
  Allow_Toggle: false
```

The permission node is not granted by default in the plugin.yml, nor would I like to give it out by default to allow players to toggle bungee chat.
