### ISSUE TITLE
1.15.2: ChatControl 9.0.1-BETA - BungeeChat connected messages are not sent upstream to the primary server's discord hooked channels.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1731]
Paper dev 367 (Spigot 1.15.2)
Waterfall dev 348 (BungeeCord)
ChatControl-Pro v9.0.1-BETA
BungeeControl v3.0.0
DiscordSRV 1.19.1-SNAPSHOT-1592862790.

* Server 1 is connected to Server 2.
* Server 1 is also connected to discord with DiscordSRV.
* Typing on Server 1 public chat sends the message to Server 2 & Discord's ``global`` defined channel.
* Typing on Server 1 admin chat with ``/chc adminchat <msg>`` sends the message to Server 2 & Discord's ``staff-chat`` defined channel.
* Typing on Server 2 public chat sends the message to Server 1 but **doesn't** send it to the discord public chat channel.
* Typing on Server 2 admin chat sends the message to Server 1 but **doesn't** send it to the discord staff chat channel.

Can bungee messages be relayed to the chatcontrol discord connected channels on the primary server with the hooks?

```
Bungee_Chat:
  #
  # Enable bungee chat for players after login automatically. They can turn it off with '/chc bc switch'
  #
  Enabled_By_Default: true
  #
  # Should we send the messages to console?
  #
  Log_To_Console: true
  #
  # Write to logs/bungee-chat.txt ?
  #
  Write_To_File: true
  #	
  # Should we allow players to toggle BungeeChat?	
  #	
  Allow_Toggle: false
```
```
# -----------------------------------------------------------------------------------------------------
BungeeCord:
  #
  # The prefix used in front of all messages coming from other servers.
  #
  Prefix: ""
  #
  # What features should have BungeeCord enabled?
  #
  Enabled_In:
    #
    # Should the messages be sent on bungeecord and back?
    # eg. Player1 is on Server1 and he will be able to message Player2 who is on Server2
    #
    Private_Messages: false
    #
    # Should we ship the messages here over bungeecord?
    #
    Admin_Chat: true
    #
    # Broadcast warning messages from rules and handlers to BungeeCord?
    #
    Rules: false
    #
    # Broadcast commands that are spied to other servers? Also toggles whether this server
    # receives spy messages?
    #
    Spy: false
    #
    # Send /me command to bungee?
    #
    Me: false
    #
    # Should we send the /chc a message to bungee?
    #
    Announcer: false
```
```
Integration:
  Discord:
    #
    # Send messages from your chat to your Discord and process incoming messages as chat messages
    #
    Enabled: true
    #
    # Should we add our formatting to the messages?
    #
    Add_Formatting: false
    #
    # Should we replace emojis with :name: or remove them
    # set to false to remove them.
    #
    Replace_Emojis_With_Raw: false
    #
    # Should we apply discord format to the BungeeChat?
    #
    Apply_Format_To_Bungee_Chat: true
    #
    # If you have chat formatting enabled, what channel on DiscordSRV should we sent
    # messages into? If you have channels enabled, see Chat_Channels below.
    #
    Chat_Channel: "global"
    #
    # What DiscordSRV channel should we send Admin_Chat into?
    #
    Admin_Chat_Channel: "staff-chat"
    #
    # What DiscordSRV channel should we send Bungee_Chat into?
    #
    Bungee_Chat_Channel: "global"
```
