### ISSUE TITLE
1.16.1: PlaceholderAPI 2.10.9 Javascript variables do not work

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#1799]
I updated to:

ChatControl 8.7.1
BungeeControl 2.3.0
PlaceHolderAPI 2.10.9

I have several Javascript variables configured in PlaceholderAPI.  Here is one example.

In PlaceholderAPI/javscript_placeholders.yml

```
blocks_flown:
  file: blocks_flown.js
  engine: nashorn
```

In PlaceholderAPI/javascripts/blocks_flown.js

```
function blocksFlown() {
    var numBlocks = "%statistic_fly_one_cm%" / 100;
    numBlocks = Math.floor(numBlocks);
    numBlocks = String(numBlocks).replace(/(.)(?=(\d{3})+$)/g,'$1,');
    return numBlocks + ' blocks';
}

blocksFlown();
```

In ChatControl/formatting.yml

```
creative:
    Bracket:
      Message: '&7[&dC&7]&r '
    Player:
      Message: '{pl_prefix}{nick}{pl_suffix}&7: &r'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&7Name&f: {javascript_full_name_for_mouse_hover}'
        - '&7Blocks Broken&f: &e{statistic_mine_block}'
        - '&7Distance Flown&f: &e{javascript_blocks_flown}'   # <-- this line
        - '&7Time Played&f: {statistic_time_played}'
        - '&9Click to PM&f {player}'
```

In the server start up logs, I get the following error:

[PlaceholderAPI] Failed to set ScriptEngine for javascript placeholder: blocks_flown

Inside Minecraft, the variables show up as:

```
{javascript_blocks_flown}
```

instead of being replaced with the value returned from the Javascript.

-----

I asked in the PlaceholderAPI Discord chat, and they said this was a ChatControl issue.  This used to work fine with the same configuration in ChatControl 8.6.6.

Any info would be much appreciated.
