### ISSUE TITLE
Combine logs with bungeecontrol

### ISSUE THREAD

**Issue by martijnpu** [kangarko/ChatControl-Pro#1845]
Hey,

I suggest a feature to combine the chatcontrol logs to 1 in combination with bungeecontrol.
If I need to look back into the logs I need to check every server because the plugin only logs what's said FROM that server, so most of the time I have only half of the conversation. 
Combining would be so much easier and less time consuming.
Another possibility is to add an option to log the incoming messages too.

Regards,
martijnpu

**Comment by kangarko** [comment]
Thanks, good suggestion

**Comment by c0wg0d** [comment]
I actually have a lot of input/feature requests in regards to logging.  ChatControl used to have a logging feature, but at some point it broke or was removed.  Ideally, I would like to have logs that contain:

All private messages, including the player who sent and the player who received the message
All sign text
All book text
All anvil renames
All chat from all servers, including the formatting specified in the ChatControl config

I use an open source plugin that I had someone develop for the sign text, book text, and anvil renames, but unfortunately it purges the logs after 7 days.  Ideally, it should retain all logs with gzip rotation.  This plugin has worked flawlessly for us over the last 4 years, so maybe you could use code from it in ChatControl to achieve this.

This is the plugin: https://github.com/jamezrin/EventLogger

I would be more than happy to help test this feature and guide its implementation if you add it to ChatControl.  I was never really happy with the previous logging feature and would love to see something more robust added.

**Comment by c0wg0d** [comment]
I would like to see more flexibility given than what you are proposing.  Most of the time, at least in a BungeeCord setup, having all chat mashed into a single file is going to be an illegible mess.

I think we should have the ability to format these logs differently than how the chat is formatted in game.  For example, if your in game chat has colors, the logs could be formatted to remove them, or if you have a channel prefix in game that's colored, allow the logs to have entire messages formatted with a specific color so they are easier to distinguish when viewing the logs with a text editor that supports colors.  We should also be able to use a wide variety of variables for replacement in the format of these messages.

I will provide a few different scenarios for what I feel would work best in the BungeeControl configuration file.  I think the ChatControl community should get a chance to weigh in on how this should be formatted, but this is my first take on it.  We can certainly move formatting into the individual Spigot/Paper configurations too if it makes sense to do so.  It also might be a good idea to provide separate MySQL support, but since I don't use MySQL, I don't know what options would fit best for that scenario, but it should be a consideration as well.

Option 1.  Chat, Private Messages, Sign text, Anvil text, and Book text from all servers go into their own combined log file.

```
All_Servers:
    Messages:
        Log_To_File: messages.log
        Format: "[%datetime%] [%server%] %player%: %message%"
    Private_Messages:
        Log_To_File: private_messages.log
        Format: "[%datetime%] [%server%] [%sender%->%receiver%] %message%"
    Sign_Text:
        Log_To_File: signs.log
        Format: "[%datetime%] [SIGN] %player%: %server%/%playerworld% @ %playerxyz%\n[%datetime%] [TEXT] %line1% %line2% %line3% %line4%"
    Anvil_Text:
        Log_To_File: anvils.log
        Format: "[%datetime%] [ANVIL] %player%: %server%/%playerworld% @ %playerxyz%.\n[%datetime%] [ITEM] %type% named %name%"
    Book_Text:
        Log_To_File: books.log
        Format: "[%datetime%] [BOOK] %player%: %server%/%playerworld% @ %playerxyz%\n[%datetime%] [CONTENTS] %booktext%"
```

Option 2.  Chat and Private Messages go into a combined file per server (example shows 3 servers named lobby, pvp, and survival) along with the Admin_Chat channel, and sign/anvil/book text goes into their own individual files from all servers.

```
All_Servers:
    Sign_Text:
        Log_To_File: signs.log
        Format: "[%datetime%] [SIGN] %player%: %server%/%playerworld% @ %playerxyz%\n[%datetime%] [TEXT] %line1% %line2% %line3% %line4%"
    Anvil_Text:
        Log_To_File: anvils.log
        Format: "[%datetime%] [ANVIL] %player%: %server%/%playerworld% @ %playerxyz%.\n[%datetime%] [ITEM] %type% named %name%"
    Book_Text:
        Log_To_File: books.log
        Format: "[%datetime%] [BOOK] %player%: %server%/%playerworld% @ %playerxyz%\n[%datetime%] [CONTENTS] %booktext%"
lobby:
    Messages:
        Log_To_File: messages_lobby.log
        Channels: [lobby, Admin_Chat]
        Format: "[%datetime%] [%server%] %player%: %message%"
    Private_Messages:
        Log_To_File: private_messages.log
        Format: "[%datetime%] [%server%] [%sender%->%receiver%] %message%"
pvp:
    Messages:
        Log_To_File: messages_pvp.log
        Channels: [pvp, Admin_Chat]
        Format: "[%datetime%] [%server%] %player%: %message%"
    Private_Messages:
        Log_To_File: private_messages.log
        Format: "[%datetime%] [%server%] [%sender%->%receiver%] %message%"
survival:
    Messages:
        Log_To_File: messages_survival.log
        Channels: [survival, Admin_Chat]
        Format: "[%datetime%] [%server%] %player%: %message%"
    Private_Messages:
        Log_To_File: private_messages.log
        Format: "[%datetime%] [%server%] [%sender%->%receiver%] %message%"
```

Option 3.  All message types go into a combined file per server (example shows 3 servers named lobby, pvp, and survival) along with the Admin_Chat channel and the Global_Chat channel, each channel having their own formatting.

```
lobby:
    Messages:
        Log_To_File: lobby.log
        Channels: [lobby, Admin_Chat, Global_Chat]
        Format:
            lobby: "&9[%datetime%] [lobby] %player%: %message%"
            Admin_Chat: "&6[%datetime%] [admin] %player%: %message%"
            Global_Chat: "&4[%datetime%] [global] %player%: %message%"
    Private_Messages:
        Log_To_File: lobby.log
        Format: "[%datetime%] [%server%] [%sender%->%receiver%] %message%"
    Sign_Text:
        Log_To_File: lobby.log
        Format: "[%datetime%] [SIGN] %player%: %server%/%playerworld% @ %playerxyz%\n[%datetime%] [TEXT] %line1% %line2% %line3% %line4%"
    Anvil_Text:
        Log_To_File: lobby.log
        Format: "[%datetime%] [ANVIL] %player%: %server%/%playerworld% @ %playerxyz%.\n[%datetime%] [ITEM] %type% named %name%"
    Book_Text:
        Log_To_File: lobby.log
        Format: "[%datetime%] [BOOK] %player%: %server%/%playerworld% @ %playerxyz%\n[%datetime%] [CONTENTS] %booktext%"
pvp:
    Messages:
        Log_To_File: pvp.log
        Channels: [pvp, Admin_Chat, Global_Chat]
        Format:
            pvp: "&3[%datetime%] [pvp] %player%: %message%"
            Admin_Chat: "&6[%datetime%] [admin] %player%: %message%"
            Global_Chat: "&4[%datetime%] [global] %player%: %message%"
    Private_Messages:
        Log_To_File: pvp.log
        Format: "[%datetime%] [%server%] [%sender%->%receiver%] %message%"
    Sign_Text:
        Log_To_File: pvp.log
        Format: "[%datetime%] [SIGN] %player%: %server%/%playerworld% @ %playerxyz%\n[%datetime%] [TEXT] %line1% %line2% %line3% %line4%"
    Anvil_Text:
        Log_To_File: pvp.log
        Format: "[%datetime%] [ANVIL] %player%: %server%/%playerworld% @ %playerxyz%.\n[%datetime%] [ITEM] %type% named %name%"
    Book_Text:
        Log_To_File: pvp.log
        Format: "[%datetime%] [BOOK] %player%: %server%/%playerworld% @ %playerxyz%\n[%datetime%] [CONTENTS] %booktext%"
survival:
    Messages:
        Log_To_File: survival.log
        Channels: [survival, Admin_Chat, Global_Chat]
        Format: 
            survival: "&8[%datetime%] [survival] %player%: %message%"
            Admin_Chat: "&6[%datetime%] [admin] %player%: %message%"
            Global_Chat: "&4[%datetime%] [global] %player%: %message%"
    Private_Messages:
        Log_To_File: survival.log
        Format: "[%datetime%] [%server%] [%sender%->%receiver%] %message%"
    Sign_Text:
        Log_To_File: survival.log
        Format: "[%datetime%] [SIGN] %player%: %server%/%playerworld% @ %playerxyz%\n[%datetime%] [TEXT] %line1% %line2% %line3% %line4%"
    Anvil_Text:
        Log_To_File: survival.log
        Format: "[%datetime%] [ANVIL] %player%: %server%/%playerworld% @ %playerxyz%.\n[%datetime%] [ITEM] %type% named %name%"
    Book_Text:
        Log_To_File: survival.log
        Format: "[%datetime%] [BOOK] %player%: %server%/%playerworld% @ %playerxyz%\n[%datetime%] [CONTENTS] %booktext%"
```
