### ISSUE TITLE
1.16.1: ChatControl doesn't respect CMI Mute

### ISSUE THREAD

**Issue by AngellitoX** [kangarko/ChatControl-Pro#1875]
Hello, when using /mute <player> from CMI, the player is unable to speak from public chat, but the private messages cancellation is bypassed.

So, basically the user is muted but he can still speak using /m <player> <test> or /msg, etc.

I have double checked and my settings look like this:

````
Mute:
  Broadcast: true
  Apply_Limits_For_Essentials_Mute: true
  Prevent:
    Writing_Books: false
    Placing_Signs: true
  Silence:
    Join_Messages: true
    Quit_Messages: true
    Death_Messages: true
  Disabled_Commands:
  - /me
  - /tell
  - /msg
  - /r
  - /m
  - /reply
  - /w
````

This was tested with latest CHC and latest CMI.
