### ISSUE TITLE
Death messages for Piglin and Hoglin doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#1885]
Costum death messages for Piglin and Hoglin are not triggered. You can enter whatever you want, the messages are simply not triggered in case of death.  All other messages work fine.

```
  Piglin:
    Killer: PIGLIN
    Message:
    - '&e{player} &7hatte keine Krone auf'
  Hoglin:
    Killer: HOGLIN
    Message:
    - '&e{player} &7wollte eigentlich nur ein Stück Schinken'
```

ChatControl 8.7.12
Paper 1.16.1 - 138
