### ISSUE TITLE
Is it possible to switch chat by putting a symbol at the beginning of a message?

### ISSUE THREAD

**Issue by sherwood2142** [kangarko/ChatControl-Pro#1896]
I really like the plugin. It provides all the functionality that I need. But before purchasing, I would like to ask one very exciting question: **Is it possible to switch chat by putting a symbol at the beginning of a message without having to switch commands?**

For example, a regular message is sent to 100 blocks - _this is a local chat_. But if you put an exclamation mark **"!"** at the beginning of the message, the message is sent to everyone within the same server - _this is a global chat_. Our players are not used to switching chat with commands. I tried to find the answer to this question, but I could not find it.

Sorry for possible mistakes, my English is not very good. I tried to ask the question in as much detail as possible.

**Comment by AngellitoX** [comment]
Hello there! Thank you for the interest on ChatControl.

Answering your question, yes, we have that feature built-in :)

````
Range: 
  #
  # Enable ranged mode?
  #
  Enabled: false
  #
  # Send a ranged message everywhere if it begins with the letter below and player has 
  # the chatcontrol.chat.globalrange permission.
  #
  # Set to none to disable. Traditionally, this used to be "!"
  #
  Global_Shortcut: "none"
  #
  # How many blocks around the sender should the players see their message?
  #
  Distance: 100.0
````

I'm marking this as solved. If you still need help, feel free to comment below or opening a new ticket. Thank you!
Angel from MineAcademy.org
