### ISSUE TITLE
1.8.8: How to setup Ranked Formats?

### ISSUE THREAD

**Issue by JorgeSilvarredonda** [kangarko/ChatControl-Pro#1900]
Im trying to setup the ranked format chats, following the wiki guide, but once uploading the formatting.yml, it gives me an error.

Server Log (Error log):
https://pastebin.com/TG4839cj

formatting.yml:
https://pastebin.com/xMVqEUa9

settings.yml:
https://pastebin.com/qMeF1idC

**Comment by AngellitoX** [comment]
Hello, your issue is because you erased the default Chat format from your formatting.yml. The wiki says that you need to add the `Ranked_Format` section to the file, not replacing the default format. 

Please try regenerating your formatting.yml and then readding the sections you modify to check if this solves your problem.

I'm marking this as solved. Consider commenting if you still need help. Thank you!
Angel from MineAcademy.org

**Comment by JorgeSilvarredonda** [comment]
Sorry, i dont know if u red my formatting.yml i sent u, i didnt removed the chat default format, its after my ranked format config, i didnt delete it. Its still there and im still having this error.

**Comment by AngellitoX** [comment]
Apologies, I just got confused because I didn't see it was below Ranked_Format.

I just checked it again and it looks like you have a `default` line below the Ranked_Format line which is not on the wiki. 

````
  Ranked_Format:
    default:
      Sender_Permission: "chat.default"
````

Where as the wiki recommends something like this
````
  Ranked_Format:
    Rank_1:
      Message: "&c[Admin] "
      Sender_Permission: "my.rank.admin"
    Rank_2: 
      Message: "&9[Mod] "
      Sender_Permission: "my.rank.mod"
    Rank_3: 
      Message: "&6[Helper] "
      Sender_Permission: "my.rank.helper"
    The_Rest: 
      Message: "&7{pl_prefix+}{player}&7: &f{message}"
````

Would you mind trying the base lines so we can pinpoint the issue? Thanks a lot!
