### ISSUE TITLE
Disable leave/join messages if peolpe are swapping servers on the bungee.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl-Pro#1903]
Ahoy

Is it possible to not send join/leave messages if people are moving between servers on the bungee? people move between them fast and its not really people leaving or joining, there still on the network.

**Comment by AngellitoX** [comment]
Hello there!

On messages.yml you can hide the join/leave messages, but it doesn't differentiate between from people moving between servers or actually leaving the network. 

If you don't mind about that, you can do this on the following lines:

````
Join_Message:
  #
  # Set to true to enable custom join messages.
  #
  Enabled: true
  #
  # Do not send the message if the player is vanished? Most vanish plugins are supported.
  #
  Ignore_Vanished: true
  #
  # The delay in ticks before displaying join message.
  # Increase to display it AFTER all messages when the player logs-in.
  #
  Delay_Ticks: 0
  #
  # That's the default message if no condition is specified or hit.
  # Use 'default' to leave unchanged, 'hide' to silence or simply write an own message, e.g. '&6{player} &7has joined the server!'
  # Is it possible to specify multiple messages that will be picked up randomly.
  #
  Message: 'hide'
````

Although, your idea sounds interesting and could be one feature added to BungeeControl for the future ChatControl v9.1 series.

Thank you.
