### ISSUE TITLE
Ignore CMI vanished players in ranged chat

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl-Pro#1929]
Currently a vanished player (using CMI vanish) can be easily revealed when some lone player uses a local chat. Normally when player uses a local chat and there is nobody nearby he will see "There is nobody within your chat range who may have seen your message." But when there is a vanished player nearby he won't see this message and thus guess that there is somebody nearby. 

CMI and ChatControl Pro are very popular plugins and it would be great to make them work together. I am sure it can be easily implemented by using CMI API, specifically CMIUser and isVanished().

**Comment by kangarko** [comment]
Thanks, are you talking about chat channels right?

**Comment by radiant-ai** [comment]
> Thanks, are you talking about chat channels right?

I am talking about ranged chat activated here:
```
Range: 
  #
  # Enable ranged mode?
  #
  Enabled: true
  #
  # Send a ranged message everywhere if it begins with the letter below and player has 
  # the chatcontrol.chat.globalrange permission.
  #
  # Set to none to disable. Traditionally, this used to be "!"
  #
  Global_Shortcut: "!"
  #
  # How many blocks around the sender should the players see their message?
  #
  Distance: 100.0
```
So I want vanished players to be hidden withing 100 range. When vanished staff member follow a lone player he can get spotted with a message in local chat.
