### ISSUE TITLE
1.12.2: Color code permissions not working in chat but are in GUI with the correct permissions given.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl-Pro#1934]
I updated to 8.8.4 and I have followed the changelogs, the Docs & read https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html. 

People with the correct permissions set to use color codes in chat like `&ctest` are getting their & icon replaced with a weird ascii symbol. 

Everything was working perfectly fine with the previous permissions, no weird symbol added, they just worked. Now they do not work after adding the new permissions and this symbol has appeared. 

But the GUI works.

![2020-09-10_19 54 50](https://user-images.githubusercontent.com/144046/92786556-3fdd3500-f3a0-11ea-921c-93ad594c418d.png)

```
- chatcontrol.command.color:
    world: PirateCraft_1
    value: true
- chatcontrol.color.DARK_AQUA:
    world: PirateCraft_1
    value: true
- chatcontrol.color.RED:
    world: PirateCraft_1
    value: true
- chatcontrol.color.WHITE:
    world: PirateCraft_1
    value: true
- chatcontrol.color.RESET:
    world: PirateCraft_1
    value: true
- chatcontrol.gui.color.DARK_AQUA:
    world: PirateCraft_1
    value: true
- chatcontrol.gui.color.RED:
    world: PirateCraft_1
    value: true
- chatcontrol.gui.color.WHITE:
    world: PirateCraft_1
    value: true
- chatcontrol.gui.color.RESET:
    world: PirateCraft_1
    value: true
```
