### ISSUE TITLE
1.16.2 | how do you make players able to be on only 1 channel?

### ISSUE THREAD

**Issue by Hilloy** [kangarko/ChatControl-Pro#1935]
Hey i bought the plugin yesterday and been configuring it for a lil bit and I wanted to know if there is any way to make it so that the players would not be able to join multiple channels but they can only see one and they will need to type a command to move to another channel

**Comment by AngellitoX** [comment]
Hello there!

First of us, thank your for purchasing it and trusting on us!

In order to answer your question, you can take a look to this section under channels.yml which I hope is exactly what you're looking for. Hope it works for you!

````
# -----------------------------------------------------------------------------------------
# How many channels can the player be at once, maximum?
#
# You can override this and give VIP's/staff more channels, see Groups in settings.yml.
# PS: There is no limit for spying channels.
# -----------------------------------------------------------------------------------------
Channel_Limits: 
  #
  # Limit for channels in which the player can write.
  #
  Write: 1
  #
  # Limit for channels which the player can read.
  #
  Read: 1
````

Marking this as solved. If you need anything else related, feel free to comment below.
Angel from MineAcademy.org
