### ISSUE TITLE
1.15.2: colored message

### ISSUE THREAD

**Issue by NaXeeo** [kangarko/ChatControl-Pro#1942]
Hi, 
I want my chat to have hover formatting from ChatControl, but I also want ranks to have writing color assigned. I've seen this https://github.com/kangarko/ChatControl-Pro/wiki/Formats article before, but I see nothing in it that can help me. I would appreciate any help.

**Comment by AngellitoX** [comment]
Hello, for the messages you can also place the hover format just the way you add it to the first part of the line as stated in the link you provided.

As for the ranks, you need to use the Ranked Format example to achieve this. 

Hope it solves your question. Have a nice day!
Angel from MineAcademy.org

**Comment by NaXeeo** [comment]
I'm sorry, but I really don't understand how to do this. 
Could you give me an example in the configuration please?

https://pastebin.pl/view/607df2c7

**Comment by kangarko** [comment]
Hey there, you can just write your own stuff and remove what you don't want from the 'Formats' section in formatting.yml to accomplish your goals.

To add hover format to the chat, look at the Hover_Event option. The 'First_Part' is simply a portion of the entire message that will get the hover effect. Example below:

```
Formats:
  Chat:
    First_Part:
      Message: "&7{pl_prefix+}"
      Hover_Event:
        Action: SHOW_TEXT
        Values:
          - "example hover message"
```

As for the ranks having their write color, I recommend you find the Second_Part of the same Chat format in the same file and replace &f with {pl_suffix} as seen below. Now you can simply use your permission plugin to give a rank/permission group certain color suffix and it will be applied as the suffix below and thus shown in the chat.

```
    Second_Part:
      Message: "{player}&7: {pl_suffix}"
      Hover_Event:
        Action: SHOW_TEXT
        Values:
          - "&7Message issued: &b{timestamp}"
          - "&7Click to send a message"
```
