### ISSUE TITLE
1.16.1 Is there an option to set a first join message in the messages.yml?

### ISSUE THREAD

**Issue by Azotha** [kangarko/ChatControl-Pro#1966]
As the title says I am wondering if it is possible to set a first time join message. I see that you can change join and leave but not first time join. Is this possible to setup with ChatControl?

**Comment by AngellitoX** [comment]
Hello!

There's is a small section called anniversary_message that could possibly guide you out.

````
    anniversary_message:
      #
      # You can also specify a Javascript condition.
      #
      Condition: 'player.getStatistic(Java.type("org.bukkit.Statistic").LEAVE_GAME) == 99'
      #
      # An example of only one message, but multi-lined.
      #
      Message: |-
        &6~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        &e&l{player} &ejoined the server 100th time!
        &6~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````
You can replace the `99` for `0` and create your first time message. Hopefully it will help you out. 

Closing this in good faith it will be solved. If you still need more help, please comment below.
Angel from MineAcademy.org

**Comment by Azotha** [comment]
Thanks!, Would it also be possible to set a sound for when the first time player joins?

**Comment by Azotha** [comment]
Also just tested changing the 99 to 0 and it didn't work, the join message I set for normal players still appeared. I also tried to change the LEAVE_GAME to JOIN_GAME and then no join message would appear after changing that.

**Comment by kangarko** [comment]
What about setting it to 1? Right now you cannot place any sound natively but you can code that in using JavaScript. Unfortunately we dont provide JavaScript coding help but if I am not mistaken the code looks something like this:

`player.playSound(Java.type('org.bukkit.Sound').SOUND_NAME, 1F, 1F)`

Replace SOUND_NAME with a value of https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html (for MC 1.16.3)

**Comment by LeehamElectronics** [comment]
I am also interested in this, however I am not sure how to test it out easily, is there a way to set a player as 'new' so when they join the server, the server thinks they are a new player? If not, I can always just create another test server to test it out on. I would also recommend that ChatControlPro 9.1.0 should include an option in the config for 'first-join-message' for simplicity.
Thanks

**Comment by LeehamElectronics** [comment]
Similar to what you already have in the config here:
```
# ---------------------------------------------------------------------------------------------------
# Welcome players to the server with a Message of The Day
# ---------------------------------------------------------------------------------------------------
Motd:
  Enabled: false

  # How long to wait before displaying after login? Used to avoid covering by other messages.
  Delay_Ticks: 2

  # Command aliases. The first one is the main label, please do not remove it!
  Command_Aliases: [motd, welcome]

  # Sound to play. Format: <bukkitSoundName>, <volume>, <pitch> 
  Sound: ENTITY_FIREWORK_LAUNCH, 1F, 0.1F

  # Below it's just an example of the message you can send to players when they log in.
  # Start a line with <center> to automatically center it.
  Message:
    - '&8*--------------------------------------------------*'
    - '&fHello {player}, we kindly welcome you to &e{server_name}&f and wish you great experience :)'
    - ''
    - '&6Version: &f{nms_version}'
    - '&6Changelog:'
    - ' &7- &fAdded ChatControl Pro plugin'
    - ''
    - '&6Help &7- &f/help &6Settings &7- &f/menu &6Web &7- &f/web'
    - '&8*--------------------------------------------------*'

  # This message is sent when a player joins for the first time. It has the same format as Message above.
  # Leave to [] to send the same message as above.
  Message_First_Time: []

  # This message is sent when a player played under a specified threshold on the server.
  # See Newcomer.Threshold section here.
  # Leave to [] to send the same message as above.
  Message_Newcomer: []
```
Except instead of being an MOTD make it so you can have the message broadcasted to all players, then we could easily setup custom messages sent out when a new player joins such as:
`mail2002 joined the server for the first time!`
rather than
`mail2002 joined the server`
