### ISSUE TITLE
Configure multiple channels with their own DIscordSRV channel + formatting help

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl-Pro#1987]
Hi, I am using latest version of ChatControlPro and I have a couple of questions.
Firstly, I am trying to setup two channels, one 'global bungee chat' and one 'admin-chat'. Each channel will have its own DiscordSRV channel associated with it. So far I have successfully got my global bungee channel working with its Discord channel, but my Admin-chat will not send and receive messages through Discord. This is my current setup:

**Settings.yml:**
```
Admin_Chat:
  Bungee: true
  Log_To_Console: true
  Write_To_File: true
  Shortcut: none
  Discord_Channel: admin
```
**DiscordSRV settings:**
```
Channels: {"global": "725267728943939611"}
Channels: {"admin": "758656655541665836"}
```

**ChatControls Channels.yml:**
https://pastebin.com/CdiLyZCu

**ChatControls Formatting.yml:**
```
# -----------------------------------------------------------------------------------------
# Enable chat formatting?
# -----------------------------------------------------------------------------------------
Enabled: true

# -----------------------------------------------------------------------------------------
# Integration with other plugins
# -----------------------------------------------------------------------------------------
Integration:
  #
  # Requires DiscordSRV. 
  #
  # Send your normal chat message to your DiscordSRV channel? If so, set the name of the
  # channel to which we shall send the message.
  #
  Discord_Channel: "global"

# -----------------------------------------------------------------------------------------
# Configuration of the default chat types in the game.
# -----------------------------------------------------------------------------------------
Formatting:
  #
  # The default chat format applied over all worlds.
  #
  Default: Chat
  #
  # If range mode is enabled, used if the ranged message starts with and "!".
  # Such messages are send to everyone (if the sender has "chatcontrol.chat.globalrange" permission).
  #
  Global: Global_Chat
  #
  # A format used in the /me command.
  #
  Me: Me
  #
  # If range mode is enabled, used to send messages to players with "chatcontrol.chat.spy"
  # permission that they normally shouldn't see (because it's outside their range).
  #
  # To spy on private messages (e.g. /tell or /mail), use /spy feature.
  #
  Spy: Spy_Chat
  #
  # If party chat is enabled, you can then spy on the messages with "chatcontrol.chat.spy" permission.
  # Requires mcMMO.
  #
  Party_Spy: Spy_Party_Chat
  #
  # Used in admin chat via "/chc ach" command, used by staff to communicate with each other.
  #
  Admin: Admin_Chat
  #      
  # Used in "/chc bungeechat" command which sends messages over bungee.
  #
  # Requires BungeeCord support.
  #
  Bungee: Chat
```

I appreciate any help I can get!
Thank you.
