### ISSUE TITLE
Question: Cancelling AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1997]
I am trying to cancel the players message using AsyncPlayerChatEvent via a (priority normal) event containing:
```java
event.setCancelled(true);
event.getRecipients().clear();
```
I have verified that it successfully reaches the cancel part however it doesn't actually cancel the message. It appears as though CHC doesn't ignorecancelled messages.

My chc pro config contains:
```yaml
Listener_Priority:
  Signs: HIGHEST
  Checker: NORMAL
  Formatter: HIGHEST
```
Is there any way to actually cancel the event? Thanks a tonne in advance 👍 
Chc Pro 8.8.5 - paper 1.16.3 build 204
