### ISSUE TITLE
Can someone remind me how to turn off players getting stuck in a dm conversation in CC?

### ISSUE THREAD

**Issue by farisjaclyn** [kangarko/ChatControl-Pro#2002]
Just recently had to re-install Chat Controls and re-write in my edits in the config.

Players are stuck in a direct message conversation and need to type in "exit" to discontinue the conversation. I want this turned off. Anyone know where it is in the config?

Suggestion: Make a discord for questions like this.
Suggestion: Don't turn this on automatically.

1.16.3 latest CC version.

Thanks

**Comment by AngellitoX** [comment]
Hello there, the information you're looking for is under settings.yml
```yaml
  # Automatically put a player into conversation mode when he types Prefix + a player's name, for example "@kangarko" in the chat?
  Auto_Start:
    Enabled: true
    # Start the conversation mode automatically when you just type /tell <player> without sending a message?
    Start_For_Empty_Tell_Command: false
    # The prefix required to start the conversation mode.
    Prefix: "@"
    # Exit this conversation mode by typing the phrase below in the chat.
    End: "exit"
```

Regarding Discord, we'll be looking for opening it probably at the end of October, once the team grows back. For now this will be our only way to ask for support.
Thank you for reaching us!
