### ISSUE TITLE
Make names change with rank

### ISSUE THREAD

**Issue by WizWazWizard** [kangarko/ChatControl-Pro#2071]
Hiya, how do I make the color of the names change with the rank? I set the rank aliases in TAB config like:

```
  wisp: '&b[WISP] &b'
  default: '&8[&7PLAYER&8] &7'
```

to make the names follow the color.

This is the format within ChatContrrol Pro - Formatting:

```
Formats:
  Chat:
    First_Part:
      Message: '{pl_prefix}'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - ''
    Second_Part:
      Message: '{nick}&7: '
```

Full Configs:
TAB: https://paste.helpch.at/igubipopaj.cs
ChatControlPro - Formatting: https://paste.helpch.at/eliwoparer.php

within TAB is how i want it to look: https://imgur.com/a/D2Rg8Iv
