### ISSUE TITLE
1.16.3: Discord multiple channels (admin + non-admin)

### ISSUE THREAD

**Issue by LizardNetwork** [kangarko/ChatControl-Pro#2087]
Hi,  
I wanted to create two channels in ChatControl:  
1) For admins only
2) For all other players

For `2)` I want to create a seperate channel so the "standard" ingame chat does not got flooded and players can choose to toggle messages on and off coming from Discord.  

When I set up DiscordSRV with these two channels ("survival-ingame", "survival-ingame-admin") ChatControl is able to send messages from the "survival-ingame" channel but won't deliver them back (from the Discord back to the ChatControl channel).  
Debugging is enabled for Discord which gives me the following output:  
```
User issued server command: /ch send survival-ingame a
[10:51:35 INFO]: [discord] Message from 'survival-ingame' channel successfuly sent to Discord.
[10:51:35 INFO]: [discord] [MC->Discord] User send message to 'survival-ingame' channel. Message: 'a'
[10:51:35 INFO]: [ChatControl 8.8.19] Command /ch send survival-ingame a took 20.57 ms

[10:51:40 INFO]: [discord] > Message not being sent to admin chat (configuration requires admin chat name: survival-ingame-admin)
```

It seems like that ChatControl always tries to take the "Admin_Chat" format for all messages from Discord to Minecraft because "survival-ingame-admin" is only set that specific format…  
Is there any way to fix this?  

settings.yml
```yaml
Admin_Chat:
  Bungee: true
  Log_To_Console: true

  # Write to logs/admin-chat.txt ?
  Write_To_File: true

  # Integration with DiscordSRV
  # The channel name on your Discord server that will receive admin messages.
  # Set "none" or leave empty to disable.
  Discord_Channel: "survival-ingame-admin"
```
  
channels.yml
```yaml
  survival-ingame:
    Format: Discord_Chat
    Console_Format: '[DC {player}] {message}'
    Log_Format: '[DC {player}] {message}'
    Discord: true
    Discord_Channel: 'survival-ingame'
```

**Comment by astirling** [comment]
I believe that your Discord channel name needs to the same as your ChatControl channel name to work.  I got around this by creating a channel I wanted for admin chat in channels.yml that had the same name as my admin channel in Discord.  Then assigned appropriate permissions for my senior staff to that channel.  

So, in your case, I would create a "survival-ingame-admin" channel in ChatControl and use that for my admin chat.

**Comment by LizardNetwork** [comment]
Thanks for trying to help!  

I tried to name those channels as I got them on Discord + DiscordSRV.  
No matter what I try, ChatControl returns `[discord] > Message not being sent to admin chat (configuration requires admin chat name: none)` .  
Messages from Minecraft to Discord will get successfully delivered but not the other way around :/
This happens while I try to send a message over the "normal" Discord channel in which all members are able to write.  
For me it seems like ChatControl tries to send every message coming from Discord to the ChatControl admin channel since the response above changes when I modify `Discord_Channel` in the settings.yml.  
  

### DiscordSRV
config.yml:
```yaml
Channels: {"discord": "xyz", "staff": "xyz", "survival-ingame" : "xyz", "survival-ingame-admin": "xyz"}
```

### ChatControl
settings.yml (tried with and without filling `Discord_Channel`):
```yaml
Admin_Chat:
  Bungee: true
  Log_To_Console: true

  # Write to logs/admin-chat.txt ?
  Write_To_File: true

  # Send a normal message directly to admin chat if it begins with the letter below
  # Set to none to disable
  Shortcut: "$"

  # Integration with DiscordSRV
  # The channel name on your Discord server that will receive admin messages.
  # Set "none" or leave empty to disable.
  Discord_Channel: "none"
```

channels.yml
```yaml
Compatibility:
  Discord:
    Control_Incoming_Messages: true
    Deny_Unknown_Channel: true
    Apply_Natural_Format_If_Online: false
```

```yaml
Channels:
  survival-ingame:
    Format: '&8[&9DC&8] {message}'
    Console_Format: '[DC {player}] {message}'
    Discord: true
  survival-ingame-admin:
    Format: '&8[&9DC A&8] {message}'
    Console_Format: '[DC {player}] {message}'
    Discord: true
```
