### ISSUE TITLE
1.16.4: Permissions needed for sign and book spy

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#2106]
There's a way to BYPASS these spy items, but assigning all of the following permissions to a player that normally has spy:

```
- chatcontrol.notify.*:
    value: false
- chatcontrol.bypass.clear:
    value: false
- chatcontrol.command.channels.spy:
    value: false
- chatcontrol.command.spy:
    value: false
- chatcontrol.notify:
    value: false
- chatcontrol.notify.me
- chatcontrol.spy.autoenable:
    value: false
- chatcontrol.spy.books:
    value: false
- chatcontrol.spy.signs:
    value: false
```
Does not have any effect, I'll still get copied on signs and books in chat with these nodes set to false.  (Needed here so I can attach a parent group with these permissions while streaming so that this sort of information doesn't  display in the video).
