### ISSUE TITLE
1.16.3: Bungee custom chat channel not working

### ISSUE THREAD

**Issue by LizardNetwork** [kangarko/ChatControl-Pro#2111]
Hi,  
I want to create a bungeewide chat channel for all admins...  
All custom bungee channels can't talk to each other, the already implemented channels can however (admin, bungee)... 
BungeeControl is installed, channels are defined on every server and in every channels.yml.  
Cannot find anything in the docs...  

Here are the configs:  
### ChatControl

```yaml
  bungee-admin:
    Format: 'xyz'
    Console_Format: '[DC A - MC A] {player} {message}'
    Discord_Format: 'yxz'
    Discord: true
    Bungee: true
```

settings.yml
```yaml
BungeeCord:
  Enabled: true
  Prefix: ''
```

### BungeeControl
config.yml
```yaml
server-names:
  lobby: "Lobby"
  skyblock: "SkyBlock"
  build: "Build"
  survival: "Survival"
messages:
  enabled: false
  ignored-servers:
  - silent_server
  send-to-target: true
  join: '&8[&a+&8] &e{player} &fjoined the network &7({to_server})'
  join-target: '&8[&a+&8] &e{player} &fjoined the game'
  leave: '&8[&c-&8] &e{player} &fleft the network &7({from_server})'
  leave-target: '&8[&c-&8] &e{player} &fleft the game'
  switch: '&8[&d>&8] &e{player} &fhas switched from &7{from_server} &fto &7{to_server}'
  switch-to: '&8[&d>&8] &e{player} &fis coming from &7{from_server}'
  switch-from: '&8[&d>&8] &e{player} &fhas switched to &7{to_server}'
```
