### ISSUE TITLE
Minecraft Version: 1.8.8 (Chat Formats)

### ISSUE THREAD

**Issue by BRIXER86** [kangarko/ChatControl-Pro#2142]
Hi, there is a bug in the chat formatting, a player is not made the correct chat formation, as you can see from the screen, how can I solve it?
C.C. pro version 8.9.4
Setup:
https://pastebin.com/Su951fzY

![image](https://user-images.githubusercontent.com/73846191/99558230-cecf8480-29c3-11eb-95a1-75672a951e66.png)

**Comment by kangarko** [comment]
Sorry what is the problem there? If you are loosing colors between each part, you need to add them manually, this is a limitation of TextComponent from Spigot

**Comment by BRIXER86** [comment]
I mean, my message (_BRIXER_) is not changed by the plugin, the message formation is different.
The message should look like this:
`&7{pl_prefix} {player} &7»&f {message}`
and it should look like this
`[Owner] _BRIXER_ » Test`
First_Part and Second_Part are not changed by the plugin

**Comment by kangarko** [comment]
Okay I see. You have two [owner] prefixes there which is coming from your permissions plugin. We only replace {pl_prefix} and see two prefixes coming from your perms so you need to edit your permission plugin to only send us one prefix.

**Comment by BRIXER86** [comment]
I do not understand what I have to do. When I send the message it looks like the plugin is not applying the changes to the message and bypasses

**Comment by kangarko** [comment]
I am sorry, what I see you have in your format is this:

```yaml
First_Part:
      # The message that is shown in the chat.
      # In this case the variable ends with +, meaning we insert a
      # space " " automatically if prefix is not empty. Note only few variables
      # have this special feature, see our GitHub.
      Message: "&7{pl_prefix}"
```

That means you will automatically get [owner] prefix. If you are getting two [owner] prefixes, this is coming from another plugin.
