### ISSUE TITLE
1.16.4:Sound_Notify makes sometimes wrong format after the ping

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl-Pro#2179]
Hi, I don't know exactly how to reproduce it, but I saw it already on one of the servers and now it's happening on my server too. When you have enabled:
```
Sound_Notify:
  Enabled: true
  Cooldown: 10 seconds
  Require_Afk: false
  Require_Prefix: none
  Sound: ENTITY_CHICKEN_EGG, 1F, 1.5F
  Color: '&a'
```
and you try "<player_name> is here", then if the default chat color is for ex. &7, then the color after ping is sometimes turned to &r probably, so it's white then - &f. Will try to capture screenshot when it happens.
