### ISSUE TITLE
Spigot 1.8.8: Join/Quit message

### ISSUE THREAD

**Issue by BRIXER86** [kangarko/ChatControl-Pro#2195]
Is it possible to put join and quit messages visible in certain worlds? If so, how do you set that I don't understand? Thanks in advance.

**Comment by kangarko** [comment]
Please see our Wiki... You can create a simple join message:

```
group test:
message:
- Hello!
```

And then apply the "require world" operator

```
group test:
require world myworld
message:
- Hello!
```

**Comment by BRIXER86** [comment]
In settings.yml I put these settings:
```
Groups:
  Enabled: true
  Group_List:
    players:
      message:
      require world Lobby
      - &8[&a+&8] {pl_prefix}{player}
```
but it didn't work i tried this other way:
```
Groups:
  Enabled: true
  Group_List:
    players:
      require world: Lobby
      message:
      - &8[&a+&8] %luckperms_prefix%{player}
```
That doesn't work either. I don't even find the wiki on how to put join and quit message which can be displayed in one world. I apologize for the inconvenience and thank you very much again.
