### ISSUE TITLE
1.13.2: Can't use /spawn when /chc mute

### ISSUE THREAD

**Issue by AngelDeaD** [kangarko/ChatControl-Pro#2239]
Minecraft Version: 1.13.2
MySQL: false
BungeeCord: true

1. admin/mod run `/chc mute`
2. user `/spawn`
3. User get `You cannot use this command while the chat is muted!`

My `Mute:`:

```
Mute:
  Broadcast: true
  Prevent:
    Writing_Books: false
    Placing_Signs: false
  Silence:
    Join_Messages: true
    Quit_Messages: true
    Death_Messages: true
  Disabled_Commands:
  - /me
  - /eme
  - /tell
  - /msg
  - /r
  - /w
  - /tell
  - /msg
  - /m
  - /pm
  - /t
  - /w
  - /r
  - /whisper
  Apply_Limits_For_Essentials_Mute: false
```

I want my users can use commands while chat is muted.
