### ISSUE TITLE
1.16.5, How can i make sound in general for the chat?

### ISSUE THREAD

**Issue by download042** [kangarko/ChatControl-Pro#2273]
What i need: When a players sends a text, with any rank, its playing a sound for erveryone. Just like the config option to play a sound when you get mentioned in chet by somebody.
Any idea how to make it?

**Comment by download042** [comment]
Obviously without the sound, when the message got caught by swear rules, so the chat message got blocked from appearing

**Comment by gone-incognito** [comment]
To do that but not have a sound play when a swear rule is triggered, add the following to the **bottom** of the list in your ``rules.txt`` file.

```yml
# Sends a sound to all players when a message in chat is sent.
match (.)*
ignore event commands|signs|book|item
dont verbose
handle as chat_sound
```

then in your ``handlers.yml`` file add 

```yml
chat_sound:
  Bypass_With_Permission: "chatcontrol.bypass.chatsound"
  Execute_Commands:
  - execute at @a run playsound minecraft:entity.arrow.hit_player ambient @a
```

If that doesn't work in your handlers, try using this

```yml
chat_sound:
  Bypass_With_Permission: "chatcontrol.bypass.chatsound"
  Sound: ENTITY_ARROW_HIT_PLAYER, 1.0, 0.1
```
I added the ``Bypass_With_Permission`` in case you wanted to create a bypass for your staff etc.

I haven't tried this before so I am not 100% sure if that will work but I see no reason for it not to work, especially if you can get people to hear a sound via a command. In which case you would just use that for the ``Execute_Commands:`` section.
