### ISSUE TITLE
1.16.5: Discord to Minecraft chat don't work

### ISSUE THREAD

**Issue by superhize** [kangarko/ChatControl-Pro#2280]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: true

I'm trying to link my in game "staff" channel to my discord staff channel, the mc->discord is working fine, but discord->mc is not working, i've already asked in DiscordSRV discord but they directed me to ChatControl support.
![WorstBunting695](https://user-images.githubusercontent.com/17607478/116909458-88ee3c00-ac44-11eb-8ce4-7dd38b4b43a6.png)

Here the discordSRV debug report if you want https://bin.scarsz.me/24c3d8b3-b514-4c18-b18e-8405f803717a#DaZkyWbFWcPouk2L6Bf3sb3vcY8Fpd67

user permission have: https://pastebin.com/Wm9wMjXM (i'm using luckperm with bungee, there is context on some permission)

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/6416466/ChatControl.zip)

**Comment by kangarko** [comment]
It says that, when a Discord message comes into Minecraft, ChatControl assumes it should go to "admin" Minecraft channel which you configured to have the Discord flag on false in your channels.yml, assuming that's just a mistake but if you need more help comment below :)

**Comment by superhize** [comment]
I don't want my message to be sent on "admin" channel, but on "staff" channel

channels.yml
```
Channels:
gobal:
    Format: '&2Global &f» {pl_prefix+}{player}&7: &f{message}'
    Bungee: true
    Discord: false
  hub:
    Format: '#68ff62HUB &f» {pl_prefix+}{player}&7: &f{message}'
    Bungee: true
    Discord: false
  staff:
    Format: '&b&lStaff &f» {pl_prefix+}{player}&7: &f{message}'
    Bungee: true
    Discord: true
  admin:
    Format: '&c&lAdmin &4» {pl_prefix+}{player}&7: &f{message}'
    Bungee: true
    Discord: false
  modo:
    Format: '#347c31Modo &f» {pl_prefix+}{player}&7: &f{message}'
    Bungee: true
    Discord: false
  anim:
    Format: '#00bda5Anim &f» {pl_prefix+}{player}&7: &f{message}'
    Bungee: true
    Discord: false
```

config from discordSRV

`Channels: {"global": "000000000000000000", "staff": "837348751462367284"}`





```
07.05 14:41:16 [Server] INFO HiZe_ issued server command: /ch join staff
07.05 14:41:20 [Server] INFO [discord] > Sending channel 'staff' message to a like-named Discord channel..
07.05 14:41:20 [Server] INFO [discord] [MC->Discord] HiZe_ send message to 'staff' channel. Message: 'h'
07.05 14:41:20 [Server] INFO [staff] HiZe_: h
07.05 14:41:30 [Server] INFO [discord] > Message not being sent to admin chat (configuration requires admin chat name: none), moving forward...
```

Why is he talking about an 'admin chat' when i'm in the 'staff' channel, i do not understand
