### ISSUE TITLE
1.16.5: Towny integration appears to have broken

### ISSUE THREAD

**Issue by KarlOfDuty** [kangarko/ChatControl-Pro#2286]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false
Towny version: 0.97.0.0
CC version: 8.10.4

Whenever a chat channel is tied to a "town" or "nation" party all chat messages return an error stating: 
"There is no plot in this location. Your message could not be sent."
![image](https://user-images.githubusercontent.com/18099825/118052427-fc99f280-b382-11eb-8ebe-ee5a003c79fe.png)

**Steps to reproduce:**

Install towny on server.

Install chatcontrol pro on server.

Set chatcontrol channels.yml "Enabled" setting to true.

Add these channels to the channels.yml config:

```yml
  town:
    Format: Global_Chat
    Party: town
  nation:
    Format: Global_Chat
    Party: nation
```

Create a new town ingame using `/t new test`

Use `/channel send town` ingame.

Type anything.

**Comment by kangarko** [comment]
Thanks, however this is an odd wontfix issue with reserved channel names I believe, correct me if I am wrong but if it's only broken for these two channel names then I assume these are reserved and we can't fix it.

**Comment by KarlOfDuty** [comment]
If you mean that changing the channel name from `town` to something else then no, that doesn't seem to solve the issue. It seems to be broken for any channel that has either of these party tags.

**Comment by KarlOfDuty** [comment]
For instance the following also doesn't work:

```yml
  somechat:
    Format: Global_Chat
    Party: town
  hello:
    Format: Global_Chat
    Party: nation
```
