### ISSUE TITLE
Adding possibility of regex input for Limited commands per <seconds>

### ISSUE THREAD

**Issue by TheJoshue** [kangarko/ChatControl-Pro#2365]
ok this is not something very big so i hope you'll consider doing it as it's very much needed
from `settings.yml`
```yml
  # Anti-spam section for commands.
  Commands:

    # How many seconds the player must wait till their next command? Set to 0 to disable.
    Command_Delay: 0

    # Limit how many messages the player can send within a certain time frame.
    Limit:
      Period: 8 seconds
      # By default they can send up to five messages within a ten seconds period.
      Max_Commands: 5
      Whitelist_Limit:
      - 'test'
```
Now here is `/test` allowed to be bypassed and typed more than 5 times in 8 seconds (any amount of execution of this command will be ok)

however, if we want to whitelist that command + any subcommand of it we need to type it in (we can't match ANY like `*`)

so with this, we then need to type in every each command if there is `/test hello` and `/test there` etc

why not adding just above or below `Whitelist_Limit` something like "`Whitelist_Limit_Regex_Expression:`"

and then we can do add:
```yml
      - '\/(test)\b (.*)'
```
which will match `test *` commands and allow them!

thank you for this i hope you'll do it because it's very needed!
