### ISSUE TITLE
MySQL database malfunction

### ISSUE THREAD

**Issue by pedroo21** [kangarko/ChatControl-Pro#288]
Hello,

Recently, this has become a problem to me. Everyday I auto-restart some of my servers, and every once in a while, ChatControl fails to load in one or some of them with the following log:

![](https://image.prntscr.com/image/P0gJ35IgTV_7OT25FTMUNA.png)

The fact is I'm not using MySQL. It is disabled in the config. Still, I get this message.

```
MySQL:
  Enabled: false
  Enabled_In:
    Channels: true
    Points: true
    Points_Save_Often: false
```

I'm unable to find a cause for it, it currently causes the server to start without the plugin, and it is fundamental for me :)
