### ISSUE TITLE
Sound notify issues

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#349]
Sound notify nolonger plays sound or even changes the text of the users name that is being announced. It sends sound for commands like /msg but when i type a users ingame name it doesnt change their text colour or even send a sound (tested this on myself and others).
This is what the config section looks like:
```
Sound_Notify:
  Enabled: true
  Cooldown: 2 seconds
  Require_Afk: false
  Require_Prefix: 'none'
  Sound: ENTITY_EXPERIENCE_ORB_PICKUP, 100F, 1F
  Color: '&e&o'
  Enabled_In_Commands:
  - msg
  - tell
  - t
  - w
  - r
```
