### ISSUE TITLE
Formatting permission issue

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#350]
This gives the prefix to all users regardless of if they have the perm or not.
```
    tester: 
      Message: "&6[test] "
      Permission: "log.test"
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "&6{player}&f, is cool"
          - "&fthis is a test message."
```
Any idea on how i can make it so only people with the perm get this?
