### ISSUE TITLE
/ignore playername not hide private messages and chat messages

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#422]
ChatControl Pro 7.5.15
This server is running Paper version git-Paper-1233 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

```
Ignore:
  Enabled: true
  Aliases:
  - ignore
  - ign
  Chat: true
  Private_Messages: true
```

```
Private_Messages:
  Enabled: true
  Bungee: true
  Aliases:
    Tell:
    - tell
    - msg
    - t
    - whisper
    - m
    - w
    Reply:
    - reply
    - r
    TogglePM:
    - togglepm
    - ignorepm
    - nopm
  Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver
```
