### ISSUE TITLE
/ignore doesn't work?

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#425]
Seems that this doesn't function... I can add permissions to people to allow them to use it, but their using it can add users to their ignore list only.  Users can not be removed from this list by any means that I can see.  (essentials had an /unignore command.,.. i would assume something like that should also exist, but if it does, it is not documented).  Adding a player to that list... does not actually ignore that player?  They can still chat messages and the person will be able to see those messages just fine.  I have no idea of the scope (if it successfully ignore/mutes their private messages or /tp requests... I have no idea, just that their chat is not blocked... which is generally what /ignore would be hoping to accomplish).

**Comment by mibby** [comment]
Can confirm that I'm also experiencing this issue. Trying to ignore players, they are still able to have their message seen with bungeecord cross-server global chat.

**Comment by kangarko** [comment]
Hello,

I am sorry for that you have issues.

**1. Un-ignore**
Players can use /ignore command twice - to ignore the player, and, if they use it the second time, to un-ignore the ignored player.

![img](https://i.imgur.com/xtuOned.png)

**2. Malfunction**
From my testing I cannot reproduce this. Please provide me more data on how you use the plugin:
* Channels / Chat Formatter enabled?
* Does it work locally and breaks over bungee only, or breaks on both?

**Comment by kangarko** [comment]
**Update:**

I had time to review this and I found out a lack of /ignore support to /chc g, /chc ach and channels on bungee mode. 

This will be added into the next version :)

**Comment by mrcoffee1026** [comment]
I'm not running bungee?  When I use /ignore a second time it just says the player is ignored again, it doesn't un-ignore... all chat messages sent by ignored user in chat still display to the user that ignored them? Yeah, based on what you said... this shouldn't be an issue but it is.  Not sure what other info you're going to need on this, I may do some more experimenting later to see if I can find an error of some sort.

**Comment by kangarko** [comment]
Hmm that's odd. Do you have Ignore.Enabled to true in settings.yml and are sure that no other plugin override this feature?

Btw, do you use MySQL?

**Comment by mrcoffee1026** [comment]
ignore is enabled (according to this part of the config, yes?  I put it below).... as far as i can tell there may be TWO plugins possibly running interference here, but chc's ignore list is displayed (and it's permission node is mentioned if there isn't permission to use it), so it seems chc is taking it over completely.  Essentials has an /ignore, and I believe so does GriefPrevention.  Essentials simply drops the ability to use the command when it exists in another plugin... only way to get it back is to make an /eignore alias.  I know a bit less about the GriefPrevention one as far as priority goes... and technically the command is /ignoreplayer and /unignoreplayer, I don't think it has /ignore as an alias.

```
# ------------------------------------------------------------------------------------------------- 
# Ability to ignore chat and private messages from certain players.
# -------------------------------------------------------------------------------------------------
Ignore: 
  Enabled: true
  
  # Please do not remove the first alias, as this is the main command label.
  Aliases: [ignore, ign]
  
  # Hide chat messages from ignored players?
  Chat: true
  
  # Do not receive private messages from ignored people?
  Private_Messages: true
```
