### ISSUE TITLE
Spy login notice still shows up on login despite spy being disabled.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#447]
ChatControlPro v7.6.6

When logging in to the server, the output ```You are now spying players' commands. Use /spy to disable.``` still shows up despite spy being disabled.

```
Spy:
  Enabled: false
  Command_Aliases:
  - spy
  - socialspy
  Format: '&8[&7spy&8] &7{player}: &7{message}'
  Channel_Prefix: '&8[&7spy&8] '
  Bungee: true
  Command_List_Works_Like_Blacklist: false
  Command_List:
  - /tell
  - /msg
  - /m
  - /t
  - /whisper
  - /r
  - /reply
  - /mail
```
