### ISSUE TITLE
Join_Message gets displayname too early / before it is set by the server.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#448]
ChatControlPro v7.6.6

Using {display_name} placeholder in the join / quit message, it displays users with a ```&8``` color grey name when they login. However after a few ticks / second, players get their proper displayname colors in tab and /list. Thus I believe the join message is being shown before player get their prefix / displayname colors.

When a player quits, it uses their proper colors.

```
Join_Message:
  #
  # Set to true to enable custom join messages.
  #
  Enabled: true
  #
  # That's the default message if no condition is specified or hit.
  # Use 'default' to leave unchanged, 'hide' to silence or simply write an own message, e.g. '&6{player} &7has joined the server!'
  # Is it possible to specify multiple messages that will be picked up randomly.
  #
  Message: '&8[&2+&8] {display_name} &fhas &2joined &fthe server.'

Quit_Message:
  #
  # Set to true to enable custom quit messages.
  #
  Enabled: true

  Message: '&8[&4-&8] {display_name} &fhas &4left &fthe server.'
```

Edit: May want to look into how much of a delay EssentialsX uses before displaying their version of custom login/quit messages, as their login message gets the displayname correctly.
https://github.com/drtshock/Essentials/blob/e6fc4590804a8687815faa2477ad1ee4b8a88edd/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L189
