### ISSUE TITLE
Anti-Bot Cooldown Not Working

### ISSUE THREAD

**Issue by MrHumblePie** [kangarko/ChatControl-Pro#458]
Hello, so I have set my options as seen below however players seem free to leave and enter regardless of these cool down settings. I have restarted the server etc and tried everything but the rejoin factor seems to have no effect at all. 

```
# -------------------------------------------------------------------------------------------------
# Reduce impact of spamming bots
# -------------------------------------------------------------------------------------------------
Anti_Bot:
  
  Cooldown: 
  
    # How many seconds the player needs to wait before logging in again?
    Rejoin: 5
    
    # How many seconds must the player wait after login to chat?
    Chat_After_Login: 0
    
    # How many seconds must the player wait after login to run commands?
    Command_After_Login: 0
  
  # Block chat until the player has moved? They can still execute commands.
  Block_Chat_Until_Moved: true
  
  # A list of commands to block until the player has moved.
  # To disable, set to: Block_Commands_Until_Moved: '[]'
  Block_Commands_Until_Moved: []
```
