### ISSUE TITLE
Priority issues

### ISSUE THREAD

**Issue by FrankHeijden** [kangarko/ChatControl-Pro#467]
ChatControl doesn't seem to block entire messages correctly when all priorities are set to `HIGHEST` in `settings.yml`:

```
Listener_Priority:
  Formatter: HIGHEST
  Checker: HIGHEST
  Signs: HIGHEST
```

e.g. the `then deny` parameter doesn't work in the rules.txt + Block_Message in handlers.yml neither.
