### ISSUE TITLE
/ignore not hide player messages in chat (/msg hide works perfectly)

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#479]
Tested with no plugins Paper 1.12.2 ChatControl v7.6.9

**Comment by kangarko** [comment]
Do you have Ignore and Private_Messages enabled in settings.yml ?

**Comment by andris155** [comment]
My config:
```
Private_Messages:
  Enabled: true
  Bungee: true
  Aliases:
    Tell:
    - tell
    - msg
    - t
    - whisper
    - m
    - w
    Reply:
    - reply
    - r
    TogglePM:
    - togglepm
    - ignorepm
    - nopm
  Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver
  Register_Reply_To_Self: true
  Toast:
    Enabled: false
    Format: '&6[{sender} &8-> &6te]{dynamic_spaces}&7{message}'
Ignore:
  Enabled: true
  Aliases:
  - ignore
  - ign
  Chat: true
  Private_Messages: true
```
