### ISSUE TITLE
JSON in motd?

### ISSUE THREAD

**Issue by download042** [kangarko/ChatControl-Pro#480]
I have this config option, but the motd are not working. :S How can i fix it? :)

Motd: 
  Enabled: true
  Delay_Ticks: 20
  Sound: ENTITY_FIREWORK_LAUNCH, 1F, 0.1F
  Message:
  - '&8*--------------------------------------------------*'
  - ''
  - '[JSON] ["",{"text":"Üzeneeeeet","color":"dark_aqua","bold":true,"clickEvent":{"action":"open_url","value":"https://www.facebook.com/risingempiremc/"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Kattints ide a facebook oldalunk megnyitásához","color":"red"}]}},"insertion":"123"}]'
  - ''
  - '&8*--------------------------------------------------*'

**Comment by kangarko** [comment]
Hey,

the JSON only works if you use it as the only part in the message:

```
Motd: 
  Enabled: true
  Delay_Ticks: 20
  Sound: ENTITY_FIREWORK_LAUNCH, 1F, 0.1F
  Message:
  - '[JSON] ["",{"text":"Üzeneeeeet","color":"dark_aqua","bold":true,"clickEvent":{"action":"open_url","value":"https://www.facebook.com/risingempiremc/"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Kattints ide a facebook oldalunk megnyitásához","color":"red"}]}},"insertion":"123"}]'
```
