### ISSUE TITLE
Broadcaster messages not line wrapping full words.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#484]
ChatControlPro 7.6.10
Paper dev 1250 (Spigot 1.12.2)

If you change a message color multiple times in the broadcaster, it does not line-wrap full words to the next line accordingly. It splits the word.

![link](https://i.imgur.com/J5aaSfH.png)

```
  Prefix: '&6&l[Example1]&r'
  Messages:
    global:
    - '&ePlay in the weekly lottery to win currency &b/lottery &eor try your
      luck at the casino for the grand prize of 100k! &b/warp Casino'
```
