### ISSUE TITLE
Vanish Problems

### ISSUE THREAD

**Issue by Phoetrix** [kangarko/ChatControl-Pro#499]
Players are able to know if a vanished player is online by saying his name in the chat because in my settings.yml I have this =>

```
Sound_Notify:
  Enabled: true

  # The time before they player will receive sound notify again.
  Cooldown: 0 seconds
  
  # Only notify if the player is afk? Requires Essentials.
  Require_Afk: false

  # Only notify when  player's name in the chat starts with the specific character.
  # Example: 'Hello @kangarko, are you there?'
  # Set to 'none' to always allow.
  Require_Prefix: 'none'
  
  # Format: bukkit_sound_name, volume (float), pitch (float)
  # If you are on MC 1.8.x or older, the default sound name was 'CHICKEN_EGG_POP'
  Sound: ENTITY_EXPERIENCE_ORB_PICKUP, 2F, 1.0F
  
  # Highlight the name of the notified player. Set to none to disable.
  Color: '&6&l'
```

Other problem: When I leave my server in vanish, the plugin don't show the leave message (from messages.yml). It's perfect but when I join the server in Vanish, the plugin show the join message (from messages.yml), aie aie aie. :(
