### ISSUE TITLE
This is the best plugin I have ever purchased. But I found plugin crash reports and language issues

### ISSUE THREAD

**Issue by nektwork** [kangarko/ChatControl-Pro#500]
It is a plugin that has a good function. It is recommended. :) However, there is a conflict between plugins.
Believe that feedback on development will be good and leave some problems.

1. The Quit_Message is not outputted because it conflicts with the Custom Join and Quit function of the CMI plugin.
When general privilege is one or when there is no authority It will work if you disable the Join and Quit function of CMI plugin, but exit messages of individual privileges of VIP player will not be displayed.

```
Join_Message:
  Enabled: true
  Message: default
  Conditions:

    Default_Message:
      Message:
        - '&8[&a+&8] &7안녕하세요, &a{player} &7님.'
      Permission: "chatcontrol.group.join.default"

    Vip_Message:
      Message:
        - '&8[&a+&8] &7안녕하세요, &a{player} &7님.'
        - '&8[&a+&8] &7어서오세요, &a{player} &7님.'
        - '&8[&a+&8] &7오늘도 오셨네요, &a{player} &7님.'
        - '&8[&a+&8] &7좋은 시간 보내시길 바랍니다, &a{player} &7님.'
        - '&8[&a+&8] &7오늘도 멋진 모습이군요, &a{player} &7님.'
      Permission: "chatcontrol.group.join.vip-1"

    Mvp_Message:
      Message:
        - '&8[&b+&8] &b안녕하세요, &3{player} &b님.'
        - '&8[&b+&8] &b어서오세요, &3{player} &b님.'
        - '&8[&b+&8] &b오늘도 오셨네요, &3{player} &b님.'
        - '&8[&b+&8] &b좋은 시간 보내시길 바랍니다, &3{player} &b님.'
        - '&8[&b+&8] &b오늘도 멋진 모습이군요, &3{player} &b님.'
      Permission: "chatcontrol.group.join.mvp"

    Vip_Nether_Message:
      World: [world_nether, hardcore_nether, another_nether]
      Message:
      - '&8[&a+&8] &7지옥에서 내가 돌아왔다. - &a{player}'
      - '&8[&a+&8] &7지옥에서 접속하셨네요, &a{player} 님.'

Quit_Message:
  Enabled: true
  Message: default
  Conditions:

    Default_Message:
      Message:
        - '&8[&c-&8] &7안녕히 가세요, &c{player} &7님.'
      Permission: "chatcontrol.group.join.default"

    Vip_Message:
      Message:
        - '&8[&c-&8] &7안녕히 가세요, &c{player} &7님.'
        - '&8[&c-&8] &7즐거운 시간이 되셨길 바랍니다, &c{player} &7님.'
        - '&8[&c-&8] &7좋은 시간 보내셨나요? &c{player} &7님.'
      Permission: "chatcontrol.group.join.vip-1"

    Mvp_Message:
      Message:
        - '&8[&c-&8] &7안녕히 가세요, &c{player} &7님.'
        - '&8[&c-&8] &7즐거운 시간이 되셨길 바랍니다, &c{player} &7님.'
        - '&8[&c-&8] &7좋은 시간 보내셨나요? &c{player} &7님.'
      Permission: "chatcontrol.group.join.mvp"
```
Here chatcontrol.group.join.default permissions only work properly. However, when deleting and testing the CMI plugin, all Quit rights worked. :)
I can very easily use the granularity feature by this authority. I want to solve these problems.

2. When deleting CMI's plugin and testing it, the color code when Quit_Message is output to the console does not apply.
https://www.spigotmc.org/attachments/upload_2017-11-22_23-52-30-png.297614/ <-- IMAGE

* NEKTWORK player is MVP user with more than default authority. However, CMI plugin During operation the **chatcontrol.group.join.mvp** permission does not work when leaving.
* RIDITCHOI player is a user with general authority. CMI plugin During operation the **chatcontrol.group.join.default** privilege works well when exiting.
However, the console has a trivial problem. Color code is not working right away.

**when the CMI plugin is disabled, it works without problems. However, I need to use this plugin in conjunction.**

3. Do you support LangUtil? When using DeathMessage on a server other than English, if you make variables of all monsters {killer} for easier management, that name is displayed as Minecraft English name.

4. The rule chat filter is optimized for English only. When used on servers other than English-speaking countries, this does not seem to work properly due to the characteristics of UTF-8.
Korean Standard: (abcdefg = it work) (ㅇㅇㅇㅇㅇㅇ = it work) (욕설욕설 = it dosen't work)

```
match 욕
then replace ****`
```

I always use this function. Can you solve it? :)

CMI (Content Management Interface) :
https://www.spigotmc.org/resources/content-management-interface-economy-mysql-sqlite-support.3742/
