### ISSUE TITLE
Warning points not being rolled off properly?

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#530]
Unless i'm just misunderstanding this feature, the settings as I have them below should be removing 8 global points and 5 spam points every 15 seconds.  That may seem excessively lax, but people were still getting kicked/banned... probably because no points are ever being removed, ever... at least not that I've seen any evidence of.  If some scheduled task needs to be running for this, it does not appear to be.  Without connecting to the database and manually editing the point value of a specific player, there doesn't seem to be any way to reduce points on any one.  It seems to me there should be a command like /chc points clear [playername] to accomplish this or to set a number when the scripts are being overly judgemental.

```
# -------------------------------------------------------------------------------------------------
# Give player warning points for violating rules/actions.
# -------------------------------------------------------------------------------------------------
Points:
  Enabled: true

  # Shall the last action be repeated until the reset task gets scheduled?
  Repeat_Last_Action: true

  # Should player only get ONE warning (the one from warning set) and not both from rules and warning sets.
  Smart_Warnings: true

  # Players will loose their warning points when you reload or shut down the server (unless you use
  # MySQL, and, once upon a time, in the reset task:
  Reset_Task:

    # The delay between taking points (in seconds). Set 0 to only reset points on plugin or server reload.
    # [TIP] If this is disabled, enable Repeat_Last_Action
    Repeat_Every_Seconds: 15

    # How much points to take from different sets. If you do not specify a set, no points will be taken from it.
    Remove:
      global: 8
      spam: 5

```
