### ISSUE TITLE
[Channels] Designated town/nation channels always visible regardless of town/nation status

### ISSUE THREAD

**Issue by v3Monsta** [kangarko/ChatControl-Pro#553]
I really didn't want to make another issue, but I don't know what else to do here. I've spent about 4 hours on the wiki trying to adjust the Listener_Priorities and testing with different permissions but nothing seems to work.

The channels TownChat & NationChat have `Party: town` and `Party: nation` set, respectively

**ChatControlPro:** 7.6.27
**Towny:** 0.92.0.1
**Spigot:** git-Spigot-bb614f8-e40c9ef (MC 1.12.2)

**Comment by kangarko** [comment]
What do you mean by town/nation status? I am not fluent with Towny, please tell me how it should be, and how it is, instead. Also you can include channels.yml so I can reproduce faster.

**Comment by v3Monsta** [comment]
Basically, I have 2 channels defined in channels.yml
```
  townChat:
    Format: TownChat
    Console_Format: "[TownChat] {player}: {message}"
    Log_Format: "{player}: {message}"
    Party: town
    
  nationChat:
    Format: NationChat
    Console_Format: "[NationChat] {player}: {message}"
    Log_Format: "{player}: {message}"
    Party: nation
```
The way TownyChat would handle town and nation chat is that if a player typed in either chat, there would be a couple checks to begin with. The first being the player must be in a town to speak in townChat, otherwise the message would be cancelled. Second, if the player was in a town but not in a nation then any nation chat messages would be cancelled. Both cancellations would provide an error message telling the player they aren't in a town or nation. Assuming the player can type in town or nation chat, the message being sent would be sent to **only** those in the players town, or if the town is in a nation, any nation chat messages should be visible to players in the same nation.

However, ChatControl doesn't seem to care whether or not players are in the same town or nation. After a couple of hours of testing I was always able to use `/channel send townChat <Message>` and anyone on the server would be able to see it despite not being in the same town as me. The same applies to nationChat.
