### ISSUE TITLE
ChatControlPro Will Not Enable

### ISSUE THREAD

**Issue by KensonPlays** [kangarko/ChatControl-Pro#564]
Here is the section of the log relating to my problem? Second link is the whole startup log.

As soon as server is up, ChatControl is disabled. Every single other plugin is green and working fine.

https://gist.github.com/anonymous/abc0e061590d8793c2085870e60bb8a1
https://gist.github.com/KensonPlays/ce92f05280634317aa09652a9f5e2a5c

**Comment by KensonPlays** [comment]
It's been almost 24 hours, and no response. This is a _**MAJOR**_ problem preventing us from going public with our server.

**Comment by kangarko** [comment]
I have a thing called life, work, family etc. Support is unpaid, however I do provide it every day. Will look into it in the evening. What’s your exact username on Spigot?

**Comment by KensonPlays** [comment]
kcmartz.

The one who had issues with this plugin in the past and ended up making a negative review. Seems like more problems are cropping up.

**Comment by kangarko** [comment]
I see. From the logs you provided it is impossible to track down the error, but it comes from the settings yaml section. Please check errors.log and post the error from there as well as it will contain more information / different trace.

**Comment by KensonPlays** [comment]
Here's the 'latest.log' section from the root server folder.
https://gist.github.com/KensonPlays/9bb40e014f2e80fdb41541052aae4159

**Comment by kangarko** [comment]
Seems like a configuration problem in messages.yml. Post me the Broadcaster section of it please.

**Comment by KensonPlays** [comment]
`Broadcaster:
  Enabled: true
  Mode: 2
  Prefix: '&8[&cKILLER &6TIPS&8]&2'
  Suffix: ''
  Delay_Seconds: 180
  Messages:
    global:
    - Hey, {player}, this server is in Open BETA! A few remaining bugs, please be
      patient!
    - Are you watching {player}'s livestream/video? Join them at IP &6&l198.55.108.161
    - Do you have suggestions for the server? Tell us on the Jurassic Kingdoms Discord: https://discord.gg/TZRaARJ
    - Join Kensons Discord at &6http://bit.ly/kp_discord_mc
    - Join Zack's Discord at &6https://discord.gg/Xy5CtWz
    - Most of the Custom Death Messages were written by our very own @ZackPower16.
      Tell him thanks!
  Sound: none
`

**Comment by KensonPlays** [comment]
https://gist.github.com/KensonPlays/68eba4addf00e35ecb09b9bebb8e3169

**Comment by kangarko** [comment]
I assume you wish to have messages on multiple lines. That would do:

```
Broadcaster:
  Enabled: true
  Mode: 2
  Prefix: '&8[&cKILLER &6TIPS&8]&2'
  Suffix: ''
  Delay_Seconds: 180
  Messages:
    global:
    - Hey, {player}, this server is in Open BETA! A few remaining bugs, please be patient!
    - Are you watching {player}'s livestream/video? Join them at IP &6&l198.55.108.161
    - Do you have suggestions for the server? Tell us on the Jurassic Kingdoms Discord https://discord.gg/TZRaARJ
    - Join Kensons Discord at &6http://bit.ly/kp_discord_mc
    - Join Zack's Discord at &6https://discord.gg/Xy5CtWz
    - |- 
      Most of the Custom Death Messages were written by our very own @ZackPower16.
      Tell him thanks!
  Sound: none
```

Notice the last "|-" special mark and the division. Let me know if you have any more questions.
