### ISSUE TITLE
Issues joining a channel automatically

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#577]
The new "Clear_Data_If_Inactive" option prevents a player from joining a channel automatically if his or her data got deleted. After typing "/ch join Corpchat" the player can read and write in the channel again automatically until his data get deleted again. Unfortunalty I dont want to bypass the joining permission, because player get really confused and upset. So could you call up the channel-joining-permission even with deleted Data or add an option to completly disable the clearing of inactive data. That would be awesome :)

Permission: `chatcontrol.autojoin.corpchat.write`
CorpChat: 
```
Channels:
  Corpchat:
    Format: CorpChat
    Console_Format: '[Corp]{player} {message}'
    Log_Format: '[Corp]{player} {message}'
```
Storage: mysql
ChatControl 7.6.33
Server Version: PaperSpigiot 1.12.2 #1310
