### ISSUE TITLE
Suggestion - Conditional based formatting.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#587]
Is it possible to support conditional based formatting? For example, force a formatting by default on everyone unless they choose a specific placeholder / tag? I'd like to add the plugin DeluxeTags to my environment and allow players to change their chat channel tag in-game.

https://www.spigotmc.org/resources/deluxetags.4390/

But players who don't select a tag, I'd like to display their group prefix by default.

```
    Default:
      Message: "&8<&7{vault_rank}&8> "       
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "{player}"
      Sender_Permission: "chatcontrol.groups.default"
    Player:
      Message: "{display_name}&f: "                 
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "{player}"
    The_Rest:
      Message: "{message}"
```

So is it possible to make it so if a player has a %deluxetags_identifier% selected, they are forced into a specific formatting (to avoid double chat tag prefix) and if they don't have any tag, use the default (to display their group rank instead)?

**Comment by kangarko** [comment]
I am sorry we don't plan to add this feature.

But, you can make your own custom javascript variable. Set Variables.Replace_In_Custom and make a simple if condition where you insert {deluxetags_identifier} directly, as it will be translated in the variable into a string, when if the string is empty the default rank will be displayed. You can read a little about custom variables in the Wiki.

**Comment by mibby** [comment]
@kangarko Interesting. A custom javascript variable definitely sounds like it can be something used as a conditional based format depending on if players have a tag selected or not. However I'm not really sure where I would begin. What would be the best way to define the if/else statement?

Ideally I'd like it so if a player has a tag selected from DeluxeTags, use {deluxetags_identifier} in the message format. Otherwise if they don't, use {vault_rank} instead.

**Comment by mibby** [comment]
@kangarko Perhaps I could pay you to create the simple if/else variable for me? :(

**Comment by kangarko** [comment]
This would work:

```
define {test}
script:
  get();

  function get() {
      var tag = "{deluxetags_identifier}";

      return tag == "" ? "{pl_prefix}" : "[" + tag + "]";
  }
```
On my machine, it won't change until /reload, can you please test it out?

**Comment by mibby** [comment]
I actually managed to get it working by creating a PlaceholderAPI javascript variable.

```
prefix:
  expression: '"%deluxetags_tag%" == ""'
  type: boolean
  true_result: '&8<&7%vault_rank%&8>'
  false_result: '%deluxetags_tag%'
```

Appreciate it though, thanks. :)
