### ISSUE TITLE
How do you hide join/quit messages for certain players?

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#598]
There used to be a feature where you would hide join/quit messages if a player had a specific permission.  I cannot find any info about this in the current documentation, and it appears as though this feature has been removed in newer versions of ChatControlPro.

I need my moderators to be able to enter and leave a server without announcing their presence so that we can observe if players are cheating.

**Comment by c0wg0d** [comment]
I tried the following config in messages.yml but it doesn't appear to work.  It doesn't show a join message at all with the following:

```
Join_Message:
  Enabled: true
  Message: default
  Conditions:
    player_message:
      Message: default
    moderator_message:
      Permission: 'chatcontrol.joinmessage.moderator'
      Message: none
```

**Comment by kangarko** [comment]
Hey, take a look at the miscellaneous section at https://github.com/kangarko/ChatControl-Pro/wiki/Permissions#miscellaneous, there you'll find universal permissions for that ;)

**Comment by c0wg0d** [comment]
I saw those permissions in the Miscellaneous section already, but that doesn't sound like what I need.  I don't want to hide the join/quit messages for normal players.  I want everyone to see join/quit messages except when certain people join the server.  If that is how those permissions work, please explain how they work because I do not understand.

**Comment by kangarko** [comment]
Hey, in the present version the logic is actually reverse, so if you give "-chatcontrol.messages.join" to the moderators they won't send any join messages. Sorry for the confusion.

**Comment by kangarko** [comment]
But, still the condition above should work. Try, instead of de-opping them or taking the perm chatcontrol.joinmessage.moderator away, giving them a negative -chatcontrol.joinmessage.moderator instead.

**Comment by c0wg0d** [comment]
I'm sorry but I need further clarification on this.  Either what you are saying flat out doesn't work or I have something misconfigured.

I went back to basics, removed all permissions, and set Join_Message.Enabled to false to false and Quit_Message.Enabled to false.  Doing this shows the join and quit messages to everyone as expected.

If I then change Join_Message.Enabled to true and Quit_Message.Enabled to true, the messages no longer show.  Even if I give players the chatcontrol.messages.join/quit permissions, they still do not show.

That is with the following config:

```
Join_Message:
  Enabled: true
  Message: default
  Conditions:
    player_message:
      Permission: 'chatcontrol.joinmessage.player'
      Message: default
    moderator_message:
      Permission: 'chatcontrol.joinmessage.moderator'
      Message: none
```

So, with the above config, I tried every combination of permissions and negating permissions I could think of and none of them will show the join/quit messages.  How does this work!?  This used to be so simple!  All I want is the default join/quit messages to show for everyone, except when moderators join/quit it doesn't announce anything to players.  Please help!

**Comment by kangarko** [comment]
When you set Join_Message or Quit_Message on false, ChatControl no longer handles it and it is left to whatever plugin you have or the Minecraft server itself (default yellow one).

There chatcontrol.messages.(...) permissions are true for everyone by default (see plugin.yml in the jar):
![a](https://i.imgur.com/NHrrcLn.png)

You do not need to modify it. There is currently a bug in the logic of those permissions - on the server itself, if you give "-chatcontrol.messages.(..)" (a.k.a negative permission), the message won't be shown at all (given no other plugin overrided it). On bungee however, if you have Bungee_Message specified (which you don't have), only people with that permission above will see that message. This is irrelevant for you but I am just taking note from my testing for myself.

The condition "Permission" only makes the condition show if the sender (the player who joined/quit) has that permission.

Please try the following set-up: 
1. Give normal players "chatcontrol.joinmessage.player" permission. 
2. Give moderators "chatcontrol.joinmessage.moderator" permission.

That very configuration will work as expected. However, I just identified that, when "default" is specified, no message is printed due to we have to delay the event by 1 tick and thus cannot send the default instruction back to the event itself. I have corrected this by using Fallback Join Message from your localization in that case.

**Comment by c0wg0d** [comment]
Thank you so much for the assistance!  I have modified my messages.yml to the following:

```
Join_Message:
  Enabled: true
  Message: default
  Conditions:
    hide_join_message:
      Permission: 'chatcontrol.hidejoinmessage'
      Message: none
Quit_Message:
  Enabled: true
  Message: default
  Conditions:
    hide_quit_message:
      Permission: 'chatcontrol.hidequitmessage'
      Message: none
```

Now all I have to do is set the permission chatcontrol.hidejoinmessage and chatcontrol.hidequitmessage for the players/groups I want to be 'hidden'.  This works flawlessly after updating to ChatControlPro 7.7.4.
