### ISSUE TITLE
Issue with me

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#638]
Action messages were formatted the way I wanted them with essentials.  I have tried disabling me in chatcontrol as well as changing the first alias... which it says not to remove.  However what it does not say is that changing the first alias will have no impact of any sort as all usages of /me get piped through this plugin whether or not it is set up to handle it or even if it is disabled.  I feel this is the same issue I've had with /ignore in the past and likely why I can't use "/ignore" as a command for essentials anymore but I'm not confident of that... since /ignore simply comes up as "Unknown command" whereas "/me something" results in a chc formatted action (or an error that the user doesn't have permissions to do it for everyone else since they don't have the chc permission set for this).

I have tried this:
```
# ------------------------------------------------------------------------------------------------- 
# A /me is a simple command allowing you to broadcast your message in a different way then chat.
# -------------------------------------------------------------------------------------------------
Me: 
  Enabled: false
  
  # Please do not remove the first alias, as this is the main command label.
  Aliases: [chcme, shout, status]
  
  # Send to bungee?
  Bungee: false  
```

In the settings file and

```
  chc:me:
  - []
  me:
  - "essentials:me $$1-"

```
in commands.yml to remedy but... apparently the actual command isn't chc:me or chatcontrol:me since those commands aren't found... or they are and these actually worked... but whatever the "real" command is, I don't know what it is so can't make an alias to kill it off, it still takes over whenever I type /me something.
