### ISSUE TITLE
NPE whenever a player logs in

### ISSUE THREAD

**Issue by Curtis73** [kangarko/ChatControl-Pro#664]
Getting a Null Pointer Exception whenever someone joins
https://pastebin.com/TZh3EHz4

**Comment by kangarko** [comment]
What's your Motd section from settings.yml?

**Comment by Curtis73** [comment]
```
Motd:
  Enabled: true
  Delay_Ticks: 2
  Sound: ENTITY_FIREWORK_LAUNCH, 1F, 0.1F
  Message:
  - '&8*--------------------------------------------------*'
  - '&fHello {player}, we would like to welcome you to &e{server_name}&f'
  - null
  - '&6Version: &f{nms_version} &7/&f 25.06.2017'
  - '&6Changelog:'
  - ' &7- &fNew Class plugin'
  - ' &7- &fChat overhaul'
  - ' &7- &fPvP world reset!'
  - '&6Help &7- &f/ticket c &6Web &7- &fpottercraft.enjin.com'
  - '&8*--------------------------------------------------*'
  Message_First_Time: []
  Message_Newcomer: []
```
Could it possibly be the "null"?
