### ISSUE TITLE
Random users acquiring Signed Book information without me granting permission.

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#678]
A second random user has reported this... where they are being given the same Book spy notification.  They DO NOT HAVE PERMISSION TO THIS.  There is something else that is either being checked for or NOT being checked for with the book spy function.  In fact ALL users have these values explicitly set:

```
- chatcontrol.commands.spy:
    value: false
- chatcontrol.spy.autoenable:
    value: false

```

Except for some members of staff.  Under these conditions, NO users should be getting notices in chat about signed books, yet they are, contents and all.   Please review the logic behind the check for this function, as there appears to be a rather large issue with it currently.
