### ISSUE TITLE
Packet filter is not working.

### ISSUE THREAD

**Issue by DeusNinja** [kangarko/ChatControl-Pro#704]
Only one I have in the packets.txt right now is

```
# Hide unknown command message.
match ^Unknown command.*
then rewrite &l&fDerp.
```

and in my settings.yml I have

```
Rules:
  Verbose: true
  Bungee: false
  Chat: true
  Commands: true
  Packets: true
  Signs:
    Check: true
    Block: true
    Drop: true
  Books:
    Check: true
    Replace: true
  Anvil:
    Check: true
    Replace: true
  Chat_Ignorer:
    Enabled: false
    Sets:
      swear:
        Ignored_By_Default: false
Regex_Strip_Colors: true. 

```
I'm using the latest protocallibs and the latest chatcontrolpro version.
While testing, I use an account that has no permissions on my server and try to run /thisisnotacommand
which results with the unknown command message, rather than derp.
