### ISSUE TITLE
Regex rules being bypassed / ignored in public and private chat.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#717]
ChatControl Pro v7.8.10
Paper dev 1410 (Spigot 1.12.2)

As of the last couple of weeks, I've been getting reports from staff and players that the chat filter has not been working in public and sometimes private chat. If I had to guess, it broke with v7.8.5 with;
```
Improve / Major | Yerr pirates make sure all rules now read and apply from top to bottom according to their files.
```

The only permission node I have given the default group is ```chatcontrol.groups.default```.
```
Rules:
  Verbose: false
  Bungee: false
  Chat: true
  Commands: true
  Packets: true
  Signs:
    Check: true
    Block: true
    Drop: true
  Books:
    Check: true
    Replace: true
  Anvil:
    Check: true
    Replace: true
  Chat_Ignorer:
    Enabled: false
    Sets:
      swear:
        Ignored_By_Default: false
```

Settings - https://paste.ubuntu.com/p/QQnGNxGSYr/
Rules.txt - https://paste.ubuntu.com/p/vcBXnNQ6BF/
Chat.txt - https://paste.ubuntu.com/p/xk2DHh3FC4/

In one example case, I am able to have a member user say ```fuck``` in public chat perfectly fine.
