### ISSUE TITLE
Option to add json hover/click events to Join & Quit message.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#757]
Would it be possible to add the ability to add json events to the join and quit messages? For example, having ```  Message: '&8[&2+&8] {display_name} &fhas &2joined &fthe server.'``` as the join message but when you hover over the display_name, have it show their playername instead?

**Comment by mibby** [comment]
@kangarko Can you help me? I can't seem to get json messages working without it erroring. Tried all of the following messages;

```
[JSON] ["",{"text":"[","color":"dark_gray"},{"text":"+","color":"dark_green"},{"text":"] ","color":"dark_gray"},{"text":"{display_name} ","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"{player}"}]}},"color":"none"},{"text":"has ","color":"white"},{"text":"joined ","color":"dark_green"},{"text":"the server.","color":"white"}]'
```

```
[JSON] {"text":"[","color":"dark_gray"},{"text":"+","color":"dark_green"},{"text":"] ","color":"dark_gray"},{"text":"{display_name} ","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"{player}"}]}},"color":"none"},{"text":"has ","color":"white"},{"text":"joined ","color":"dark_green"},{"text":"the server.","color":"white"}'
```

```
[JSON] {"text":"[","color":"dark_gray"},{"text":"+","color":"dark_green"},{"text":"] ","color":"dark_gray"},{"text":"{display_name} ","hoverEvent":{"action":"show_text","value":{"text":'',"extra":[{"text":"{player}"}]}},"color":"none"},{"text":"has ","color":"white"},{"text":"joined ","color":"dark_green"},{"text":"the server.","color":"white"}'
```

**Comment by kangarko** [comment]
As the error says, change "color":"none" to "color":"reset" as ChatColor has no such field: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/ChatColor.html

**Comment by kangarko** [comment]
Also, here's a great website for validation and formatting: https://jsonformatter.curiousconcept.com/

**Comment by mibby** [comment]
@kangarko Thanks. Changing the message to the following works;

```
Join_Message:
  Enabled: true
  Message: '[JSON] ["",{"text":"[","color":"dark_gray"},{"text":"+","color":"dark_green"},{"text":"] ","color":"dark_gray"},{"text":"{display_name} ","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"{player}"}]}},"color":"reset"},{"text":"has ","color":"white"},{"text":"joined ","color":"dark_green"},{"text":"the server.","color":"white"}]'
Quit_Message:
  Enabled: true
  Message: '[JSON] ["",{"text":"[","color":"dark_gray"},{"text":"-","color":"dark_red"},{"text":"] ","color":"dark_gray"},{"text":"{display_name} ","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"{player}"}]}},"color":"reset"},{"text":"has ","color":"white"},{"text":"left ","color":"dark_red"},{"text":"the server.","color":"white"}]'
```

However I'm now running into another issue. The Join message is being sent before it can get the player's full displayname changes - i.e. any nicknames and colors set by the person's primary rank group. It displays their name white and without any nickname.

Would it be possible to delay the join message a couple ticks until all prefix / display_name data is registered on the player? Essential's join message does not have this issue when player's login.
