### ISSUE TITLE
Chat messages wont be logged to console anymore

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#759]
Since version 7.8.15 messages won't be logged to the console anymore. Of course there is the \plugins\ChatControl\logs\chat.log folder where everything is logged accurately. But messages won't show up in the normal server log, which I really need due to some dependencies. The problem only affects puplic messages, private ones are logged correctly. Is this just a bug or did I missed something in the configuration?

PaperSpigiot 1.12.2 #1416

**Comment by kangarko** [comment]
Please try setting Console_Filter.Enabled to false.

**Comment by kangarko** [comment]
Test the next version with Console_Filter.Filter_System_Out on false.

**Comment by TheoRetisch1** [comment]
Sorry for the delay. Console_Filter.Filter_System_Out doesn't work for me. Puplic messages won't show up in the normal server log, but private messages do. The problem doesnt exist in version 7.8.9 of ChatControl, in that version everything is logged correctly in the server log.

config: 
```
Console_Filter:
  Enabled: false
  Log: false
  Filter_Console_Messages:
  - - glizer
  Filter_System_Out: false
```
ChatControl: 7.8.21
PaperSpigiot: 1.12.2 #1431

**Comment by kangarko** [comment]
From what I see you have double "-  -", remove that.

Also, check the next version in which when the Filter_System_Out is on false, no change is applied and so you should see your chat in the console normally.

**Comment by TheoRetisch1** [comment]
Still won't work for me and I can't find the mistake. Could you help me? :)

Channels.yml: 
 ```
 Corpchat:
    Format: CorpChat
    Console_Format: '[Corp]{player} {message}'
    Log_Format: '[Corp]{player} {message}'
```

setting.yml: 
```
Console_Filter:
  Enabled: false
  Log: false
  Filter_Console_Messages:
  - glizer
  Filter_System_Out: false
```

Under ChatControl\logs\channels everything is logged correctly but I need the output in the normal chatlog :/

ChatControl 7.8.24, no erros in the console
PaperSpigiot 1.12.2 - 1445
