### ISSUE TITLE
Chat delay

### ISSUE THREAD

**Issue by wingcwf** [kangarko/ChatControl-Pro#809]
> [14:24:47 INFO]: [ChatControl 7.8.27] loading component part [Chat.Prefix] took 252 ms
> [14:24:47 INFO]: [ChatControl 7.8.27] creating component [Chat] took 412 ms
> [14:24:48 INFO]: [ChatControl 7.8.27] loading component part [Chat.Prefix] took 266 ms
> [14:24:48 INFO]: [ChatControl 7.8.27] creating component [Chat] took 442 ms

Delayed the message by 1s

**Comment by kangarko** [comment]
Does it always happen or only after the server starts?

Please post me your formatting.yml uploaded to pastebin.com

**Comment by wingcwf** [comment]
always happens
https://pastebin.com/bDmB8avP

**Comment by kangarko** [comment]
Some variables you use in your Chat.Prefix part of the format are lagging:

````
Prefix:
      Message: "&7[&clv.{askyblock_island_level}&7] {pl_prefix}"      
      Hover_Event:
        Action: SHOW_TEXT
        Values:
          - '{userprefix}{player}'
          - '&8&m================='
          - '&8├ &f空島等級: &e{askyblock_island_level}'
          - '&8├ &f玩家殺數: &c{placeholderapi_statistic_player_kills}'
          - '&8├ &f玩家殺怪數: &4{placeholderapi_mvdw_stat_mkills}'
          - ''
          - '&8├ &f擁有金錢: &a${money_formatted}'
          - '&8├ &f遊玩時間: &6{placeholderapi_statistic_hours_played}小時'
          - ''
          - '&7( 點擊傳送到玩家的島嶼 )'
      Click_Event:
        Action: RUN_COMMAND
        Value: "/is warp {player}"
````

Remove them one-by-one to find out what causes the issue.
