### ISSUE TITLE
Can´t disable Parrot_Repeated message

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#858]
Hejo,
I want to disable the parrot_repeat message, therefore I set the specific options to 0. Unfortuntaly the message shows up anyway if somebody writes the same message someone posted just recently in a short amount of time, even if the mesage is whitelisted.

 ```
 Chat:
    Message_Delay: 0
    Delay_Points:
      Warn_Set: fastmessages
      Amount: 0
    Similar_Percentage_Block: 0
    Similarity_Message_Check_Count: 0
    Similarity_Points:
      Warn_Set: spam
      Amount: 0
    Whitelist_Similarity:
    - hello
    - hey
    Whitelist_Delay:
    - test
    Limit:
      Period: 10 seconds
      Max_Messages: 8
    Parrot:
      Enabled: true
      Delay: 20 ticks
      Minimum_Similarity: 85
  Regex_In_Whitelists: false
```

ChatControl: 7.9.3
PaperSpigiot 1.12 #1499
