### ISSUE TITLE
Join/Quit message hierarchy/conditions don't seem to work.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#881]
Hello! I found out about the awesome Joni/Quit message formatting, so Im starting simple to get this to work, but it seems to not trigger any of the conditions. 
It always fires off the "normal_message", I have given myself the chatcontrol.joinmessage.staff permission for staff_message but that dousn't work, checking for crews does not work either (normal_message_crew) I have made sure {simpleclans_in_clan} outputs "yes".
Is there a way to set weight of these messages? order doesn't seem to matter, I have tried in different orders. or is there a way to check all the conditions first and then fire a default if not?
```
Join_Message:
  Enabled: true
  Message: default
  Conditions:
    staff_message:
      Permission: chatcontrol.joinmessage.staff
      Message:
      # - '&8[&2+&8] &rWelcome &b{player} &rto the server!'
      # - '&8[&2+&8] &rBless &9{player} &rfor joining!'
      # - '&8[&2+&8] &rAll say hey to &e{player} &rfor joining!'
      - '&2>> &bWatch out, &r{pl_prefix}{nick}{pl_suffix}&b just boarded the ship!'
    normal_message:
      World:
      - PirateCraft_1
      - PirateCraft_1_the_end
      Message: '&2>> &eAvast ye! {pl_primary_group} &r{pl_prefix}{nick}{pl_suffix} &ehas come aboard!'
    normal_message_crew:
      World:
      - PirateCraft_1
      - PirateCraft_1_the_end
      Condition: '"{simpleclans_in_clan}" == "yes"'
      Message: '&2>> &eAvast ye! {pl_primary_group} &r{pl_prefix}{nick}{pl_suffix} &eof &7{clan}&e has come aboard!'
    hells_message:
      World:
      - PirateCraft_1_nether
      Message: '&2>> &eAvast ye! {pl_primary_group} &r{pl_prefix}{nick}{pl_suffix} &ehas entered the depths of hell!'
    jubileum_message:
      Condition: player.getStatistic(Java.type("org.bukkit.Statistic").LEAVE_GAME) == 99
      Message: |-
        &6~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        &e&l{player} &ejoined the server 100th time!
        &6~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Quit_Message:
  Enabled: true
  Message: default
  Conditions:
    normal_message:
      World:
      - PirateCraft_1
      - PirateCraft_1_the_end
      - PirateCraft_1_nether
      Message: '&4<< &eScallywag&r {display_name} &equit th` battle!'
    staff_message:
      Permission: chatcontrol.joinmessage.staff
      Message:
      - '&8[&2<&8] &b{player} &rleft the server'
      - '&8[&2<&8] &9{player} &rjust quit the game. Good bye!'
      - '&8[&2<&8] &rSay goodbye to &e{player} &rfor leaving!'
```
