### ISSUE TITLE
PM Spy does not work corretly

### ISSUE THREAD

**Issue by Fabrimat** [kangarko/ChatControl-Pro#922]
I don't know if i messed up some configuration but when somebody does /msg i see just the command without the receiver (spy.format in config)
![image](https://user-images.githubusercontent.com/13642582/45352761-89c89000-b5b9-11e8-8c00-567656637b03.png)
But if somebody use /r I see it correctly
![image](https://user-images.githubusercontent.com/13642582/45352815-a9f84f00-b5b9-11e8-8742-da632c92ab4e.png)

My spy config:
```
Spy:
  Enabled: true
  Command_Aliases:
  - spy
  - socialspy
  Format: "&8[&5spy&8] &7{player}: &7{message}"
  Format_PM: "&8[&5spy&8] &7[{player}] -> [{receiver}]: &7{message}"
  Channel_Prefix: '&8[&5spy&8] '
  Command_List_Works_Like_Blacklist: false
  McMMO: true
  Log_McMMO: false
  Books: false
  Signs: false
  Command_List:
    - /tell
    - /msg
    - /t
    - /whisper
    - /w
    - /r
    - /reply
```
