### ISSUE TITLE
Denoting "chatcontrol.chat.read" and "chatcontrol.chat.write" does not work.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#927]
Hey!
I setup a world specific permission to denote "chatcontrol.chat.read" and "chatcontrol.chat.write", not op, not admin. and I can still read & write in the normal chat.

**Comment by matt11matthew** [comment]
Are you able to attach your config and instructions on how to reproduce the issue?

**Comment by kangarko** [comment]
These perms were not applied for chat channels. This is now fixed. Let me know if issues persist. 

Sincerely apologies for a late answer.

**Comment by FrozenBeard** [comment]
No worries brother, let me test it :)

**Comment by FrozenBeard** [comment]
Nope. I can still talk as a player/not op with the permission set to false in that world.

```
name: default
permissions:
- chatcontrol.chat.read:
    world: locker
    value: false
- chatcontrol.chat.write:
    world: locker
    value: false
```

I have also set the "newcomer" section to the same world to see if this will block the chat & commands.
But that still lets players talk in that world!

```
Newcomer: 
  
  # How much time must a player spend on the server to no longer be considered as a newcomer?
  # Set to 0 minutes to disable
  Threshold: 999 days
    
  # In which worlds should we enable this feature? Useful when you have a newbie world.
  # Example: [survival, nether, end]. Set to ["*"] to enable in all worlds.
  Worlds: ["locker"]
  
  Restrict_Chat: 
    # Block newcomers from chatting ?
    Enabled: true
    
    # What messages should we allow anyways? Case-insensitive. Split by ", ". Example: [quit, end]
    Whitelist: []
    
  Restrict_Seeing_Chat: 
    # Prevent newcomers from seeing chat messages?
    Enabled: true
  
  Restrict_Commands:
    # Prevent newcomers from using commands?
    Enabled: true
    
    # Reverse the functionality of the Whitelist?
    Blacklist: false
    
    # What commands to allow anyways?
    # If Blacklist is enabled, only the commands here will be blocked.
    Whitelist: 
      - /login
      - /l
      - /register
      - /reg
      - /helpop
      - /help
      - /?
```
