### ISSUE TITLE
Staff alert doesn't show the actual word

### ISSUE THREAD

**Issue by Sir-Will** [kangarko/ChatControl-Pro#99]
hey,
the staff notification doesn't show the uncensored word:
![](http://i.imgur.com/WQf2lYG.jpg)

Is there a new permission for that which I couldn't find?

**Comment by kangarko** [comment]
I cannot replicate. The default permission 'chatcontrol.notify.swear' is enough and player with it will be able to see the uncenzored message. Ensure you're on latest ChatControl Pro.

**Comment by Sir-Will** [comment]
Hm, I did test it with 7.0.11 and I have the permission. I wouldn't see the gray text if I don't have the permission.

**Comment by kangarko** [comment]
Have you modified the rule or handler? If so, please post them. If unsure, post your handlers.yml and rules.txt files.

**Comment by Sir-Will** [comment]
rules.txt
```
match <some regex>
id 6
then replace *****
handle as swear
```
handlers.yml
```
swear:
  Bypass_With_Permission: chatcontrol.bypass.swear
  Ignored_In_Commands:
  - //
  - /auction
  - /auc
  - /register
  - /reg
  - /login
  - /l
  Player_Warn_Message: '&cSwearing is prohibited on this server.'
  Replace_Word: '*****'
  Write_To_File: logs/swears.txt
  Staff_Alert: 'chatcontrol.notify.swear &8[&7Swear/ID {ruleID}&8] &7{player}: &f{message}'

```
