### ISSUE TITLE
Ignore_Commands Setting is Ignored

### ISSUE THREAD

**Issue by delbertina** [kangarko/ChatControl-Pro#991]
I'm not sure when this started, but cannot get the "Ignore_Commands" part of a handler to work. Have tried deleting the ChatControl plugin folder complete and let it regen a new one and the default settings still dont work correctly. Tried with and without any other plugins also. Have noticed this setting name has changed a time or two so maybe this is an undocumented change that never made it to the default file. I'm using the very latest plugin release in 1.13 paper.

**Snip of the default config for clarity**
```
swear:
  #
  # Ignore players with permission.
  #
  Bypass_With_Permission: "chatcontrol.bypass.swear"
  #
  # Do not filter commands below:
  #
  Ignore_Commands: 
    - // # WorldEdit
    - /brush
    - /auction
    - /auc
    - /register
    - /reg
    - /login
    - /l
```

**Steps to reproduce:**
1. Delete ChatControl plugin folder (optional)
2. Restart server (optional)
3. Do /brush [swear word] (or any of the commands in the config list with a swear word included too)
4. Get warned in chat and in console.
