### ISSUE TITLE
Tab-complete Feature for 1.13

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#995]
Could you add a new tab-complete list handler. Whereby we specify a few things:
1) blocking a command from showing up the tab-complete list.
2) blocking a command in the tab-complete list if a player has `x` permission.
3) blocking multiple commands from the tab-complete list if player has `x` permission
```yaml
BlockTabComplete:
   #Blocks commands in general for everyone.
   Commands:
   - help
   - spy
   - socialspy
   #Blocks commands if the user doesn't have the permission node specified.
   Permissions:
       test.permission.node: command
       test.permission.node2: command1, command2, command3
```
This should be relatively easy to implement as it would be done in something like this:
```java
 @EventHandler
    public void onSendCommand(PlayerCommandSendEvent event) {
        if(event.getPlayer().hasPermission(x)){
            event.getCommand.remove(x);
            // or event.getCommand.removeAll/removeIf(string -> string.equalsIgnoreCase(x))
        }
    }
```
